cursorless-dev/cursorless

src/processTargets.ts
I needed some work to do with the extension and I noticed a 'good first issue' label on #23, so I thought I'd take a stab at it.
Turns out this code also involves the bug I reported with indicating the last subpiece by its index #9, so I included a commit for that as well. This was caused by the `endIndex` getting wrapped to 0, so I added an explicit check which will reset it back to the max value. This assumes `endIndex` doesn't ever need to be 0, which I think is a safe assumption? 
Hopefully this is helpful! Let me know if you'd approach any of this differently!
Closes #9 
Closes #23
=> Add character subpiece transformation

package.json
This got left behind in the rename from mauve to purple. It is currently breaking extension activation.
=> Fix purple color setting name

package.json
This extension should be safe to use in untrusted workspaces; it has no vulnerable settings and doesn't try to execute any code from the workspace
=> Add support for untrusted workspaces

src/targetUtils.ts
Using `take that` when no that mark exists led to null/undefined exception. Added if statement to check and provide better error message
=> Improved error message ensureSingleEditor

src/Types.ts, src/actions/SetBreakpoint.ts, src/actions/index.ts
@pokey 
When starting a new debug session `debug.breakpoints` is empty even though I can see old breakpoints besides the lines. This makes it so you can't remove existing breakpoints for a few attempts. After that it all works fine.
=> Added action set breakpoint

src/processTargets.ts, src/test/suite/fixtures/recorded/subtoken/chuckFirstCharVest.yml, src/test/suite/fixtures/recorded/subtoken/chuckFirstWordVest.yml, src/test/suite/fixtures/recorded/subtoken/chuckLastCharVest.yml, src/test/suite/fixtures/recorded/subtoken/chuckLastWordVest.yml, src/test/suite/fixtures/recorded/subtoken/chuckSecondWordVest.yml, src/test/suite/fixtures/recorded/subtoken/chuckSixthCharVest.yml, src/test/suite/fixtures/recorded/subtoken/clearFirstCharVest.yml, src/test/suite/fixtures/recorded/subtoken/clearFirstWordVest.yml, src/test/suite/fixtures/recorded/subtoken/clearLastCharVest.yml, src/test/suite/fixtures/recorded/subtoken/clearLastWordVest.yml, src/test/suite/fixtures/recorded/subtoken/clearSecondWordVest.yml, src/test/suite/fixtures/recorded/subtoken/clearSixthCharVest.yml
`chuck second word air` well now remove the underscore in a snake case token.
=> Added leading and trailing delimiters to subtoken

.github/workflows/test.yml, package.json, src/test/runTest.ts, src/test/suite/recorded.test.ts
This runs tests for linux, mac, and windows on every PR and push to master.
Tests occasionally flake out, it seems like adding a 100ms wait after decoration set up solves this. I've run the tests a few times successfully now. The timeout could be smaller, but things are pretty bad on the macos runner which is pretty dang slow. I'm guessing because of this:
```
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
```
[From what I've been able to read](https://github.com/actions/virtual-environments/issues?q=is%3Aissue+sort%3Aupdated-desc+macos+opengl+is%3Aclosed), it doesn't seem like we're going to be able to do much about that...?
=> Test on PR and push to master

src/Types.ts, src/actions/InsertEmptyLines.ts, src/editDisplayUtils.ts, src/performInsideOutsideAdjustment.ts, src/processTargets.ts, src/test/suite/fixtures/recorded/positions/chuckAfterBlockVest.yml, src/test/suite/fixtures/recorded/positions/chuckAfterLineVest.yml, src/test/suite/fixtures/recorded/positions/chuckBeforeBlockAir.yml, src/test/suite/fixtures/recorded/positions/chuckBeforeLineAir.yml
* Line decorations are now always shown for the correct line
* Decorations for line/paragraph with position before/after uses non line decoration. 
- This means that the decorations aren't shown for empty lines
* Before line and paragraph are adjusted to not include indentations on line with text
- `chuck before line` keeps indentation
* Fixed line decoration on float command
=> Updated how line decorations are shown

src/extension.ts, src/languages/index.ts, src/processTargets.ts
See also https://github.com/pokey/vscode-parse-tree/pull/5
=> Let parse tree errors through

src/languages/index.ts, src/processTargets.ts, src/test/suite/fixtures/recorded/languages/typescript/takeEveryArgAir.yml, src/test/suite/fixtures/recorded/languages/typescript/takeEveryArgBat.yml, src/test/suite/fixtures/recorded/languages/typescript/takeEveryArgRam.yml, src/test/suite/fixtures/recorded/languages/typescript/takeEveryItem5.yml, src/test/suite/fixtures/recorded/languages/typescript/takeEveryKey.yml, src/test/suite/fixtures/recorded/languages/typescript/takeEveryValue.yml
=> Check ancestors for every

src/setSelectionsAndFocusEditor.ts
We now focus the editor after setting the selection because otherwise you see an intermediate state where the old selection persists
=> Fix cross-split selections

.vscode/launch.json, src/editDisplayUtils.ts, src/extension.ts, src/getExtensionApi.ts, src/test/suite/recorded.test.ts
Depends on https://github.com/pokey/vscode-parse-tree/pull/8
Closes #175
Closes #173
=> Retry tests and remove sleep

src/actions/EditNewLine.ts, src/checkCommandValidity.ts, src/extension.ts, src/processTargets/processModifier.ts, src/processTargets/processSelectionType.ts, src/test/runTest.ts, src/test/suite/fixtures/recorded/selectionTypes/drinkCell.yml, src/test/suite/fixtures/recorded/selectionTypes/drinkCellEach.yml, src/test/suite/fixtures/recorded/selectionTypes/pourCell.yml, src/test/suite/fixtures/recorded/selectionTypes/pourCellEach.yml, src/typings/Types.ts, src/util/targetUtils.ts
Depends on https://github.com/pokey/cursorless-talon/pull/63
=> Add cell selection type

src/canonicalizeTargets.ts, src/languages/cpp.ts, src/languages/csharp.ts, src/languages/java.ts, src/languages/python.ts, src/languages/typescript.ts, src/test/suite/fixtures/recorded/languages/typescript/clearFunk.yml, src/test/suite/fixtures/recorded/languages/typescript/clearFunk2.yml, src/test/suite/fixtures/recorded/languages/typescript/clearLambda.yml, src/test/suite/fixtures/recorded/languages/typescript/clearLambda2.yml, src/test/suite/fixtures/recorded/languages/typescript/clearLambda3.yml, src/test/suite/fixtures/recorded/languages/typescript/clearLambda4.yml, src/typings/Types.ts
=> Fix anonymous functions

src/actions/CommandAction.ts, src/util/setSelectionsAndFocusEditor.ts
Unfortunately, we aren't able to set focus back to where it was before, eg a search box.  Maybe this argues for switching back to our own copy implementation?
=> Fix copy when focus is not on editor

docs/parse-tree-patterns.md, src/extension.ts, src/languages/python.ts, src/test/suite/fixtures/recorded/languages/python/chuckType.yml, src/test/suite/fixtures/recorded/languages/python/chuckValue.yml, src/test/suite/fixtures/recorded/languages/python/clearEveryValue.yml, src/util/nodeFinders.ts
Fixes #257 
Mixed feelings about this solution.  There is no way to exclude two types, for example.
The alternative would be to explicitly list the types that we want to allow user to use "value" field with.  There are about 7
=> Fix "take every value" in python

.github/workflows/test.yml, README.md, src/languages/index.ts
See https://sfconservancy.org/news/2020/jun/23/gitbranchname/ for why
=> master => main

src/languages/cpp.ts, src/languages/java.ts, src/languages/json.ts, src/languages/python.ts, src/languages/typescript.ts, src/test/suite/fixtures/recorded/languages/python/chuckKey.yml, src/test/suite/fixtures/recorded/languages/python/chuckKey2.yml, src/test/suite/fixtures/recorded/languages/python/chuckValue.yml, src/test/suite/fixtures/recorded/languages/typescript/chuckKey.yml, src/test/suite/fixtures/recorded/languages/typescript/clearKey.yml, src/util/nodeMatchers.ts, src/util/nodeSelectors.ts
Allows saying "chuck key" and having the trailing `:` cleaned up
=> Add suffixedMatcher; use for keys

package.json, src/canonicalizeTargets.ts, src/core/constants.ts
"pink" will become the default term for this color in the next few weeks (see https://github.com/pokey/cursorless-talon/issues/66), and we will change the default color to be more obviously pink.  Hoping to reduce cognitive dissonance for colors
See also https://github.com/pokey/cursorless-talon/pull/75
=> Rename purple to pink

src/core/tokenizer.ts, src/test/suite/tokenizer.test.ts
=> Fix color tokens

src/core/Decorations.ts
I adjusted the measurements to fix the math bug for my setup, but unfortunately different users will be affected proportional to the square of the ratio of their character width to the ceiling of the width, so they'll unfortunately need to do their own tweaking if they've adjusted their defaults
Note that the hats have moved up very slightly, but it is minor, and we will tweak these heights in #269 anyway
Fixes #110
Fixes #92 
And possibly #78
=> Fix SVG alignment and click box

src/core/tokenizer.ts, src/test/suite/tokenizer.test.ts
Since repeatable symbols was before identifier `_a` was split into two tokens
=> Put identifier before repeatable symbols

src/languages/python.ts, src/languages/typescript.ts, src/test/suite/fixtures/recorded/languages/python/chuckValue2.yml, src/test/suite/fixtures/recorded/languages/python/clearValue.yml, src/test/suite/fixtures/recorded/languages/python/clearValue2.yml, src/test/suite/fixtures/recorded/languages/typescript/takeValue3.yml, src/test/suite/fixtures/recorded/languages/typescript/takeValue4.yml
This has a couple known issues in typescript:
1. It will select the semicolon if your cursor is right before it
2. It will not remove the leading space if you say "chuck value"
I think worth merging because it is an improvement.  Can file the others for later
=> Support value for return value

src/core/Decorations.ts, src/core/FontMeasurements.ts, src/core/editStyles.ts, src/extension.ts, src/typings/Types.ts, src/util/graphFactories.ts
=> Dispose of decorations

src/languages/java.ts, src/languages/python.ts, src/languages/typescript.ts, src/test/suite/fixtures/recorded/languages/java/takeCondition.yml, src/test/suite/fixtures/recorded/languages/java/takeCondition2.yml, src/test/suite/fixtures/recorded/languages/java/takeCondition3.yml, src/test/suite/fixtures/recorded/languages/python/takeCondition.yml, src/test/suite/fixtures/recorded/languages/python/takeCondition2.yml, src/test/suite/fixtures/recorded/languages/typescript/takeCondition.yml, src/test/suite/fixtures/recorded/languages/typescript/takeCondition2.yml, src/test/suite/fixtures/recorded/languages/typescript/takeCondition3.yml, src/typings/Types.ts, src/util/nodeMatchers.ts, src/util/nodeSelectors.ts
=> Added conditions scope type

src/processTargets/processSelectionType.ts, src/test/suite/fixtures/recorded/positions/chuckAfterHarp.yml, src/test/suite/fixtures/recorded/positions/chuckAfterLook.yml, src/test/suite/fixtures/recorded/positions/chuckAir.yml, src/test/suite/fixtures/recorded/positions/chuckBeforeAir.yml, src/test/suite/fixtures/recorded/positions/chuckBeforeEach.yml, src/test/suite/fixtures/recorded/positions/chuckBeforeHarp.yml
Delimiter was not aggressive enough for positions before/after. Many times `chuck before token` would fail. 
Updated delimiter code and added additional tests.
=> Updated leading and trailing delimiters for before and after positions

src/core/NavigationMap.ts, src/processTargets/index.ts, src/processTargets/processSelectionType.ts, src/test/suite/fixtures/recorded/selectionTypes/bringAirToAfterColumnBatPastFine.yml, src/test/suite/fixtures/recorded/selectionTypes/bringAirToBeforeColumnBatPastFine.yml, src/test/suite/fixtures/recorded/selectionTypes/bringAirToColumnBatPastFine.yml, src/test/suite/fixtures/recorded/selectionTypes/bringAirToEndOfColumnBatPastFine.yml, src/test/suite/fixtures/recorded/selectionTypes/bringAirToStartOfColumnBatPastFine.yml, src/test/suite/fixtures/recorded/selectionTypes/postColumnWhaleUntilEach.yml, src/test/suite/fixtures/recorded/selectionTypes/takeColumnAirPastEach.yml, src/test/suite/fixtures/recorded/selectionTypes/takeColumnLookPastAir.yml, src/test/suite/fixtures/recorded/selectionTypes/takeColumnUntilEach.yml, src/test/suite/fixtures/recorded/selectionTypes/takeColumnWhaleBetweenRam.yml, src/typings/Types.ts
Selection type to create multiple selections in a column between two targets instead of a continuous range
Right now doesn't do anything without a ranged target.
fixes #345
=> Column selection type

src/languages/typescript.ts, src/test/suite/fixtures/recorded/languages/typescript/takeState2.yml
At the moment a `statement` in typescript will just captured a block/body of if statements and loops. Disabling statement block makes the ancestral crawl find the entire statement instead.
=> Disabled statement block on typescript

docs/contributing/adding-a-new-language.md, docs/contributing/test-case-recorder.md
Some links got messed up when I reorganized the `docs` directory
=> Fix doc links

.vscode/settings.json, src/actions/BringMoveSwap.ts, src/core/inferFullTargets.ts, src/processTargets/index.ts, src/processTargets/modifiers/processModifier.ts, src/processTargets/processSelectionType.ts, src/test/suite/fixtures/recorded/actions/bringAirAndBatAndCap.yml, src/test/suite/fixtures/recorded/actions/bringArgueFineAndZip.yml, src/test/suite/fixtures/recorded/actions/bringArgueOxAndZipToAfterJustLeper.yml, src/test/suite/fixtures/recorded/actions/bringLineHarpAndWhale.yml, src/test/suite/fixtures/recorded/actions/bringVest.yml, src/test/suite/fixtures/recorded/actions/callFine.yml, src/test/suite/fixtures/recorded/actions/callVest.yml, src/test/suite/fixtures/recorded/actions/moveVest.yml, src/test/suite/fixtures/recorded/hatTokenMap/bringHarpTakeWhale.yml, src/test/suite/fixtures/recorded/inference/bringLineLookToJustAir.yml, src/test/suite/fixtures/recorded/languages/typescript/clearType2.yml, src/test/suite/fixtures/recorded/updateSelections/bringFine.yml, src/test/suite/fixtures/recorded/updateSelections/bringWhale.yml, src/typings/Types.ts, src/util/canonicalizeTargets.ts
=> Implemented strict here selection type

src/processTargets/modifiers/surroundingPair/findSurroundingPairParseTreeBased.ts, src/test/suite/fixtures/recorded/surroundingPair/parseTree/typescript/clearPair10.yml, src/test/suite/fixtures/recorded/surroundingPair/parseTree/typescript/clearPair9.yml, src/util/treeSitterUtils.ts
If an angle bracket is contained in an error node, we relax the requirement that it be the first / last child of its parent
=> Handle angle brackets within an error node

src/actions/Fold.ts
This reverts commit 8117983d6ed5b3242855264e6f89079ebad4ecb6 because it broke "fold every state" when one of the statements was a single line
=> Filter out single-line targets for `fold` action

src/actions/Rewrap.ts, src/test/suite/fixtures/recorded/actions/curlyRepackRound.yml, src/test/suite/fixtures/recorded/actions/squareRepackHarp.yml, src/test/suite/fixtures/recorded/actions/squareRepackLeper.yml, src/test/suite/fixtures/recorded/actions/squareRepackPair.yml, src/test/suite/fixtures/recorded/actions/squareRepackThis.yml
The `that` mark is now set to be the full delimited range, rather than just the delimiters, to be consistent with the way "wrap" works
=> Fix `that` mark for rewrap action

src/core/HatAllocator.ts
Change timeout for all hat map redecorations to 40ms because it was too jittery at 16ms.  Was slowing down dictation for me, and rapidly pressing the up arrow also caused the hats to flail
=> Fix hat map jitter

package.json, src/core/HatAllocator.ts
I personally like my debounce delay a bit longer, as otherwise it can cause lagging.  I've reset the default to 50ms, which is what it used to be before I bumped it to 175ms to account for longer command phrases, but now it is configurable for users who want a smaller / larger value
=> Configurable debounce delay

src/actions/SetBreakpoint.ts, src/test/suite/breakpoints.test.ts
Line level breakpoints are always on character 0. This new implementation is consistent with the built in vscode breakpoint functions in regard to line and inline breakpoints.
=> Fixed bug where line breakpoint would use incorrectly character

.github/workflows/deploy.yaml, package.json, src/scripts/prepareForExtensionPublish.ts, yarn.lock
This is the first step in our moved to continuous delivery (#17). This PR adds a Github action which automatically releases the extension every time we merge to main. It uses a version number which is automatically generated from the commit number. 
We will move to automatically deploying the talon files once we moved to a mono repo. It is safe to just begin with the extension publication because we are careful about backwards compatibility in this direction
=> Publish extension on merge to main

.github/workflows/deploy.yaml
to `v2`, because I was getting complaints from the actions runner
=> Bump actions/setup-node action

.github/workflows/deploy.yaml, src/test/suite/fold.test.ts, src/test/suite/scroll.test.ts
=> Added tests for visible ranges(scroll, fold)

docs/user/README.md
This adds the rewrap command to the user docs. As an aside, I had a hard time getting it recognized over wrap and had to switch the command to "switch".
=> Add rewrap command to docs

src/languages/php.ts, src/languages/typescript.ts, src/test/suite/fixtures/recorded/languages/php/changeValue7.yml, src/test/suite/fixtures/recorded/languages/php/chuckValue10.yml, src/test/suite/fixtures/recorded/languages/typescript/changeValue.yml
Fixes #325 
I also slipped in support for PHP since I missed it when I originally added the language.
=> Support value scope for yield statements in TS and PHP

.vscodeignore
Not necessary to ship the website with the extension.  Shouldn't be too big of a deal in CI, but locally packaging extension you end up with massive bundle if you've built website before locally
=> Exclude website from extension

cursorless-talon/src/cheatsheet/cheat_sheet.py, cursorless-talon/src/cheatsheet/sections/actions.py, docs/user/README.md
=> Update docs to clarify that all actions require a target

README.md
Missed the relative links.  There could be more; it's a bit tough to grep for them.  I believe this PR tackles all the ones that are on the main landing page
=> Fix more doc links

website/docusaurus.config.js
Should fix #668. I haven't tested this yet.
=> docusaurus.config.js: Remove trailing slash on url

src/actions/EditNewLine.ts, src/processTargets/modifiers/scopeTypeStages/ContainingSyntaxScopeStage.ts, src/processTargets/targets/BaseTarget.ts, src/processTargets/targets/DocumentTarget.ts, src/processTargets/targets/LineTarget.ts, src/processTargets/targets/NotebookCellTarget.ts, src/processTargets/targets/ParagraphTarget.ts, src/processTargets/targets/ScopeTypeTarget.ts, src/test/suite/fixtures/recorded/actions/drinkArg.yml, src/test/suite/fixtures/recorded/actions/drinkBlock.yml, src/test/suite/fixtures/recorded/actions/pourArg.yml, src/test/suite/fixtures/recorded/actions/pourBlock.yml, src/typings/target.types.ts, src/util/targetUtils.ts
In regards too `drink/pour`
Instead of relying on the built in vscode commands for inserting new lines we can now insert our own delimiters. 
`drink arg`, `pour funk` etc is now working. Some of the scope types don't have proper delimiters but as soon as we add that to the scope type definition they will automatically work with this action. 
1. Should we rename the action now that we can insert before arbitrary delimiters and not just lines?
2. The default implementation right now is to insert a new line delimiter. If we still want to use vscode command as default just change `getEditNewLineContext` in `BaseTarget.ts` to:
```
return {
command: this.isBefore
? "editor.action.insertLineBefore"
: "editor.action.insertLineAfter",
};
```
Fixes #242
=> Support delimiter based edit newline

src/processTargets/processTargets.ts, src/test/suite/fixtures/recorded/compoundTargets/chuckLineRiskSliceMade.yml
```
short
something longer
something even longer
```
"chuck line R slice M"
All three lines are completely removed because the new targets are still lines. This is a regression in how vertical range target is supposed to work. The solution is to always default to a plain target except in the case of a position target.
=> Fixed regression in vertical range target

package.json
The process proved to be too unreliable.  I've made it a script that needs to be run manually.  We can revisit if we find ourselves frequently adding packages; today it's a fairly rare occurrence.
=> Stop updating licenses automatically

schemas/cursorless-snippets.json
I was hoping to get errors in my snippet json because we switched `insertionScopeType` to `insertionScopeTypes`, but didn't, because we were allowing additional properties
=> Disallow additional properties in snippets

cursorless-talon/src/actions/actions_callback.py, cursorless-talon/src/actions/actions_makeshift.py, cursorless-talon/src/actions/get_text.py, cursorless-talon/src/actions/wrap.py, cursorless-talon/src/cheatsheet/cheat_sheet.py, cursorless-talon/src/command.py, cursorless-talon/src/compound_targets.py, cursorless-talon/src/csv_overrides.py, cursorless-talon/src/marks/mark.py, cursorless-talon/src/modifiers/matching_pair_symbol.py, cursorless-talon/src/modifiers/position.py, cursorless-talon/src/modifiers/sub_token.py, cursorless-talon/src/positional_target.py
I fixed all the easy ones.  There were a few that I couldn't fix due to the way Talon works, eg not having `self` arg in action classes
=> Fix type hints

src/processTargets/modifiers/ItemStage/ItemStage.ts, src/processTargets/modifiers/ItemStage/tokenizeRange.ts, src/test/suite/fixtures/recorded/itemTextual/clearItem10.yml, src/test/suite/fixtures/recorded/itemTextual/clearItem11.yml, src/test/suite/fixtures/recorded/itemTextual/clearItem9.yml, src/test/suite/fixtures/recorded/itemTextual/clearItemDrip.yml
=> Tweaks to #709

.github/workflows/deploy.yaml, cursorless-nx/nx.json
Nx isn't properly caching outputs because we're outputting to a nonstandard location.  This means that when it tries to use the cache, it doesn't restore the artifacts we actually need, so in particular the cheatsheet html file doesn't get created.
At some point we need to figure out how to get the cache working, but for now let's just skip their cloud caching mechanism.  It's just used on deploy and our build is fairly cheap so should be fine for now
=> Skip nx cache

src/processTargets/modifiers/ItemStage/ItemStage.ts, src/test/suite/fixtures/recorded/itemTextual/chuckItem3.yml, src/test/suite/fixtures/recorded/itemTextual/chuckItem4.yml, src/util/rangeUtils.ts
Fixes #834
This actually broke 45 tests. Basically we get off by one errors on the that mark.
`const value = "Hello world";` `"chuck vest"`. At the moment the that mark will be an empty selection adjacent the equal sign. If we prefer the leading range it will be adjacent the const instead.
=> Remove empty trailing line for "chuck item" with trailing comma

src/test/suite/backwardCompatibility.test.ts, src/test/suite/breakpoints.test.ts, src/test/suite/crossCellsSetSelection.test.ts, src/test/suite/editNewCell.test.ts, src/test/suite/fold.test.ts, src/test/suite/followLink.test.ts, src/test/suite/groupByDocument.test.ts, src/test/suite/intraCellSetSelection.test.ts, src/test/suite/prePhraseSnapshot.test.ts, src/test/suite/recorded.test.ts, src/test/suite/scroll.test.ts, src/test/suite/shouldUpdateFixtures.ts, src/test/suite/standardSuiteSetup.ts, src/test/suite/toggleDecorations.test.ts, src/util/sleep.ts
Instead of sleeping the same amount of time every time we run a test, we double the sleep every time
Fixes #845
=> Fix CI failures by adding sleep backoff

src/languages/java.ts, src/test/suite/fixtures/recorded/languages/java/clearComment.yml
Backwards compatible with existing parser; can drop that once https://github.com/cursorless-dev/vscode-parse-tree/pull/37 is released
=> Update Java patterns for new tree-sitter grammar

.vscodeignore
The assets for the status bar icon were being excluded by our .vscodeignore, so this is what we currently see in status bar in production:
=> Fix status bar icon

website/package.json, website/typedoc.js, website/yarn.lock
Our contributor documentation ended up with lots of undesired pages because it included node_modules in the api docs.  Thus, we had things like mocha types, vscode types, etc
This PR also updates docusaurus, now that v2.0.0 is out of beta
=> Exclude node_modules from typedoc and upgrade docusaurus

src/test/suite/fixtures/recorded/languages/javascript/clearCoreWhale.yml
Looks like we don't have any Javascript tests 😳.  We have been relying on the fact that the parse tree is just a subset of Typescript.  Which is true...unless you update the Typescript parser and forget to update the Javascript parser 😅
This new test is currently breaking because we forgot to update the Javascript parser when we updated the Typescript parser.  It should start passing when https://github.com/cursorless-dev/vscode-parse-tree/pull/46 is released
=> Add javascript pair test

src/test/suite/recorded.test.ts
This PR just lays the ground work for #967 by adding support for tests that don't include a final `that` mark.
=> Handle tests with no final `that` mark

src/testUtil/TestCase.ts, src/testUtil/TestCaseRecorder.ts
Also makes it so that the final `that` mark is excluded by default
=> Add test case recorder flag to exclude the final `that` mark

cursorless-talon/src/marks/lines_number.py, cursorless-talon/src/modifiers/ordinal_scope.py, cursorless-talon/src/modifiers/relative_scope.py, cursorless-talon/src/number_small.py
Fixes #1021
Note that I opted to make our own capture because I figured if the user wasn't using our `row` commands at all, they'd be surprised when all of a sudden their `number_small` changed in VSCode
Decided to just add something to wiki for simplicity https://github.com/cursorless-dev/cursorless/wiki/Troubleshooting#custom-number_small-capture-is-not-being-used-by-cursorless
=> Workaround for `number_small` performance on old knausj version

src/processTargets/targetUtil/insertionRemovalBehaviors/TokenInsertionRemovalBehavior.ts, src/test/suite/fixtures/recorded/actions/chuckArgMadeAndAirAndJustSoon.yml, src/test/suite/fixtures/recorded/languages/css/chuckValue.yml, src/test/suite/fixtures/recorded/languages/css/chuckValue2.yml, src/test/suite/fixtures/recorded/languages/css/chuckValue3.yml, src/test/suite/fixtures/recorded/languages/rust/chuckCallNear.yml, src/test/suite/fixtures/recorded/languages/rust/chuckFunkNameFine.yml, src/test/suite/fixtures/recorded/languages/rust/chuckListOne.yml, src/test/suite/fixtures/recorded/languages/rust/chuckName.yml, src/test/suite/fixtures/recorded/languages/rust/chuckName2.yml, src/test/suite/fixtures/recorded/languages/scss/chuckValue.yml, src/test/suite/fixtures/recorded/languages/scss/chuckValue2.yml, src/test/suite/fixtures/recorded/languages/scss/chuckValue3.yml, src/test/suite/fixtures/recorded/positions/chuckAir.yml, src/test/suite/fixtures/recorded/selectionTypes/chuckSmallPaintFine.yml, src/test/suite/fixtures/recorded/selectionTypes/chuckSmallPaintSoap2.yml
=> Token removal range based upon merging of tokens or not

src/core/languageTokenizers.ts, src/core/tokenizer.ts, src/core/tokenizer.types.ts, src/processTargets/modifiers/scopeTypeStages/SubTokenStages.ts, src/processTargets/modifiers/subToken.ts, src/test/suite/fixtures/recorded/subtoken/chuckLastWord.yml, src/test/suite/fixtures/subtoken.fixture.ts, src/test/suite/subtoken.test.ts, src/util/addDecorationsToEditor.ts, src/util/regex.ts
Fixes #975 
Also adds support for unicode sub words. At the moment our tokenizer and sub word regex doesn't match.
=> Update sub word regex/splitter

src/core/commandRunner/CommandRunner.ts, src/extension.ts, src/ide/ide.types.ts, src/ide/spies/SpyConfiguration.ts, src/ide/spies/SpyIDE.ts, src/ide/spies/SpyMessages.ts, src/ide/vscode/VscodeConfiguration.ts, src/ide/vscode/VscodeIDE.ts, src/ide/vscode/VscodeMessages.ts, src/test/suite/fakes/ide/FakeConfiguration.ts, src/test/suite/fakes/ide/FakeIDE.ts, src/test/suite/fakes/ide/FakeMessages.ts, src/test/suite/recorded.test.ts, src/test/suite/tokenGraphemeSplitter.test.ts, src/testUtil/TestCase.ts, src/testUtil/TestCaseRecorder.ts, src/typings/Types.ts, src/util/graphFactories.ts, src/util/makeGraph.ts, src/util/typeUtils.ts
Adds `ide.messages`, which abstracts showing messages to the user. Also adds support for spying the ide, and uses it to allow spying which messages were sent during recording or while running tests.
=> Add support for spying ide; add `ide.messages`

src/extension.ts
I pasted the code into the description of https://github.com/cursorless-dev/cursorless/issues/45.  No reason to have it polluting our `extension.ts`
=> Remove unused off-screen modification protection

.github/workflows/deploy.yaml, .github/workflows/test-docs.yml, .github/workflows/test.yml
This bumps the GitHub Actions using node12 to the latest versions using node16. This should squash ~most~ all of the actions-related warnings, such as the ones seen on https://github.com/cursorless-dev/cursorless/actions/runs/3302625117
=> .github/workflows: Bump actions for node16

src/languages/markdown.ts, src/test/suite/fixtures/recorded/languages/markdown/chuckName.yml, src/test/suite/runTestSubset.ts
For better performance.  Must be merged at the same time as https://github.com/cursorless-dev/vscode-parse-tree/pull/56
=> Switch tree-sitter-markdown dependency

src/processTargets/modifiers/scopeHandlers/TokenScopeHandler.ts, src/test/suite/containingTokenTwice.test.ts, src/test/suite/fixtures/recorded/subtoken/takeFirstChar2.yml, src/util/regex.ts
=> Fixed bug with reusing regex in token preference

src/util/notebook.ts
Looks like the experimental notebook api has been deprecated. Solved it for now by adding an additional field name. 
We should really think about updating to vscode version 1.68 and get these as proper types.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1a72ad27159fcb85c0d951e6ff2fd19f47017ab0/types/vscode/index.d.ts#L12793
=> Added new notebook editor field

src/test/initLaunchSandbox.ts
Doesn't work on windows otherwise
If this has any problem on mac or Linux we could make this boolean only be true on windows
=> Added shell:true to init launch sandbox

cursorless-nx/libs/cheatsheet/src/lib/components/formatCaptures.tsx
=> Tweak cheatsheet variable coloring

cursorless-talon/src/apps/cursorless_vscode.py, src/actions/Find.ts, src/ide/vscode/textLine.test.ts
=> Limit the amount of text used in `scout` and `scout all`

.github/workflows/test-docs.yml, .github/workflows/test.yml
I don't think there's really any reason to not run tests on stacked PRs.
This removes the PR base branch restriction on the test workflows.
=> workflows: Run CI on stacked PRs

src/apps/cursorless-vscode-e2e/suite/keyboard/basic.test.ts, src/keyboard/KeyboardCommandsTargeted.ts
We were using the equivalent of "take this" to set the target to be the current selection when you enter cursorless keyboard mode, but that obviously broke when we made "take this" refer to token.  This PR effectively changes the command we use to `"highlight just this"`
=> Fix modal keyboard interface broken by #1094

src/ide/vscode/VscodeFocusEditor.ts
- Fixes #981
Just doesn't bother with notebook scrolling, as the regular `revealLine` on the cell's `TextEditor` seems to be good enough
=> Fix long notebook cell jumping

src/apps/cursorless-vscode-e2e/suite/fold.test.ts, src/apps/cursorless-vscode-e2e/suite/followLink.test.ts, src/apps/cursorless-vscode-e2e/suite/keyboard/basic.test.ts, src/apps/cursorless-vscode-e2e/suite/pourAcrossSplit.test.ts, src/apps/cursorless-vscode-e2e/suite/recorded.test.ts, src/ide/vscode/VscodeTextEditorImpl.ts, src/libs/vscode-common/testUtil/openNewEditor.ts
- This one most likely broke in #1143, but I'm not certain
=> Fix `"pour"` across split

docs/contributing/CONTRIBUTING.md
=> fix broken link syntax in readme

src/actions/Highlight.ts
The new behaviour broke my video recorder, because it didn't clear highlights if I targeted something on other side of screen
=> Change `"highlight nothing"` to target all editors

package.json, src/core/commandRunner/CommandRunner.ts, src/extension.ts, src/ide/vscode/VscodeHighlights.ts, src/ide/vscode/VscodeIDE.ts, src/ide/vscode/vscodeShowQuickPick.ts, src/libs/common/ide/PassthroughIDEBase.ts, src/libs/common/ide/fake/FakeIDE.ts, src/libs/common/ide/types/QuickPickOptions.ts, src/libs/common/ide/types/ide.types.ts, src/libs/common/ide/util/messages.ts, src/testUtil/TestCaseRecorder.ts
Also simplifies workflow for adding a new directory to recorded test case dir by adding an inline option:
=> Remove vscode references from test case recorder

docs/contributing/CONTRIBUTING.md
Workaround for https://github.com/cursorless-dev/cursorless/issues/1291, which is caused by https://github.com/microsoft/vscode/issues/176372.
=> Workaround for VSCode profile creation bug

packages/cursorless-engine/core/Debug.ts, packages/cursorless-engine/languages/clojure.ts, packages/cursorless-engine/languages/csharp.ts, packages/cursorless-engine/languages/elseIfExtractor.ts, packages/cursorless-engine/languages/getNodeMatcher.ts, packages/cursorless-engine/languages/getTextFragmentExtractor.ts, packages/cursorless-engine/languages/html.ts, packages/cursorless-engine/languages/json.ts, packages/cursorless-engine/languages/latex.ts, packages/cursorless-engine/languages/markdown.ts, packages/cursorless-engine/languages/php.ts, packages/cursorless-engine/languages/python.ts, packages/cursorless-engine/languages/ruby.ts, packages/cursorless-engine/languages/rust.ts, packages/cursorless-engine/languages/scss.ts, packages/cursorless-engine/languages/ternaryBranchMatcher.ts, packages/cursorless-engine/languages/typescript.ts, packages/cursorless-engine/processTargets/modifiers/surroundingPair/findSurroundingPairParseTreeBased.ts, packages/cursorless-engine/processTargets/modifiers/surroundingPair/index.ts, packages/cursorless-engine/typings/Graph.ts, packages/cursorless-engine/typings/Types.ts, packages/cursorless-engine/util/nodeFinders.ts, packages/cursorless-engine/util/nodeMatchers.ts, packages/cursorless-engine/util/nodeSelectors.ts, packages/cursorless-engine/util/treeSitterUtils.ts
=> Add `type` annotations to tree-sitter imports

packages/common/ide/fake/FakeGlobalState.ts, packages/common/ide/types/Clipboard.ts, packages/common/ide/types/State.ts, packages/cursorless-engine/core/updateSelections/updateSelections.ts, packages/cursorless-vscode-core/ide/vscode/VscodeClipboard.ts, packages/cursorless-vscode-core/ide/vscode/VscodeGlobalState.ts, packages/cursorless-vscode-core/ide/vscode/VscodeOpenLink.ts, packages/cursorless-vscode-e2e/suite/recorded.test.ts, packages/cursorless-vscode/constructTestHelpers.ts, packages/vscode-common/getExtensionApi.ts
Extracted from #1281 with fixes
=> `Thenable` => `Promise`; tweak clipboard mock

packages/common/src/ide/fake/FakeIDE.ts, packages/common/src/ide/normalized/NormalizedIDE.ts, packages/common/src/testUtil/getFixturePaths.ts, packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/testCaseRecorder/takeHarp.yml, packages/cursorless-vscode-e2e/src/suite/testCaseRecorder.test.ts, tsconfig.base.json
The test case recorder broke in #1281 due to the fact we're now launching extension in subdirectory called `dist` rather than top-level repo.  This PR fixes it
=> Fix test case recorder

packages/cursorless-org-docs/README.md
=> Fix link in README for cursorless-org-docs

packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts, packages/cursorless-vscode-e2e/src/suite/testCaseRecorder.test.ts
This PR fixes a bug with our test case recorder.  If an exception is thrown during command processing before we inject a spy ide during `TestCaseRecorder.preCommandHook`, we don't set the `originalIde` member variable on `TestCaseRecorder`.  During `TestCaseRecorder.finallyHook`, we unconditionally call `injectIde(this.originalIde)` even in the case of an error, which means that we will inject an `undefined` ide, so Cursorless becomes completely broken, because `ide()` is now `undefined`, so we get an error about not having injected ide for every single subsequent command
This PR just checks that `this.originalIde != null` before trying to inject it
=> Fix bug with injected ide in test case recorder

.github/workflows/deploy.yaml, .github/workflows/test-docs.yml, .github/workflows/test.yml, .vscode/launch.json, packages/common/src/ide/normalized/NormalizedIDE.ts, packages/common/src/testUtil/getCursorlessRepoRoot.ts, packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts, packages/cursorless-vscode-e2e/src/suite/setupFake.ts
- Makes it so that we can use `getCursorlessRepoRoot` anywhere
- Normalizes snippets dir so that recording snippets tests has same snippets available as in actual testing
=> Fix `getCursorlessRepoRoot`; normalize snippet dir

packages/cursorless-engine/src/languages/latex.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/clearElm.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/clearEndTag.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/clearName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/clearName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/clearStartTag.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/clearTags.yml
Adds support for "tags", "start tag", "end tag", and "name tags" to LaTeX environments
...and once again regretting making our internal identifiers too specific 🤦‍♂️
=> Add support for xml scopes to LaTeX

.pre-commit-config.yaml
This decreases the frequency of pre-commit.ci autoupdates.
=> pre-commit: Bump autoupdates from weekly to monthly

packages/cursorless-engine/src/processTargets/targets/PositionTarget.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/positions/pourIfState.yml
We have functionality that computes minimum indentation when doing a "pour", but we don't use it if the delimiter is `\n` because we switch to using the editor's newline insertion to handle things like indenting after a line ending in `:` in Python.  However, if the user is explicitly pouring something that is multiple lines, then I argue that it is safe to do our own insertion.  This change enables things like properly dedenting after an if statement in Python
=> `PositionTarget`: consider minimum line indentation when pouring multiline target

package.json
The website `*.tsx` files weren't being linted in CI, as `pnpm test` isn't doing a recursive `pnpm lint`:
https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/package.json#L18
A single `eslint` run should be enough to lint the entire TypeScript codebase with the correct configs, I think.
=> Lint *.tsx from top-level lint script

cursorless-talon/src/actions/replace.py
The type hint `list[str] or dict` always evaluated to `list[str]` at runtime.
`cursorless_replace` was only ever used in homophones and reformat, both of which always pass a list.
=> [talon] Fix confusing replace action type hint

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, package.json
- Partially addresses #640
- Supercedes #1400
=> pre-commit: Switch to GitHub action; add eslint fixer

.pre-commit-config.yaml, docs/contributing/test-case-recorder.md, package.json, packages/cursorless-engine/package.json, packages/cursorless-engine/src/scripts/transformRecordedTests/index.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/decorations/carveLineHarp.yml
=> Add recorded test formatter to pre-commit

packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
Our test runs currently look like this when they're passing:
That's not particularly reassuring, especially for new contributors.  This PR fixes that.  It's not necessary to log errors from command runner, because the exception bubbles all the way up so we see the stack trace anyway
=> Remove scary-looking error message in test runs

packages/cursorless-engine/src/cursorlessEngine.ts, packages/cursorless-engine/src/languages/LanguageDefinition.ts, packages/cursorless-engine/src/languages/captureNames.ts, packages/cursorless-engine/src/processTargets/ModifierStageFactoryImpl.ts, packages/cursorless-engine/src/processTargets/modifiers/ItemStage/ItemStage.ts, packages/cursorless-engine/src/processTargets/modifiers/ItemStage/getIterationScope.ts, packages/cursorless-engine/src/processTargets/modifiers/SurroundingPairStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterTextFragmentScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeTypeStages/BoundedNonWhitespaceStage.ts, packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts
Allows specifying which nodes should be treated as raw text from the perspective of surrounding pairs.  For example
```scm
(comment) @textFragment
```
- see eg https://github.com/cursorless-dev/cursorless/pull/1448/files#diff-83dc43cab688debd9b40743b835d49f7a047d393df9da5bb39e354f39aa09966R7-R8
=> Support specifying text fragments via queries

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BaseScopeHandler.test.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BaseScopeHandler.ts
=> Fix bugs in scope handling with `skipAncestorScopes`

packages/cursorless-engine/src/languages/typescript.ts, packages/cursorless-engine/src/util/nodeSelectors.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearCoreElement3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearElement.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEndTag.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearStartTag.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearTags.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/takeCoreElement.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/takeCoreElement2.yml
=> Added typescript language support for jsx fragment node

cursorless-talon/src/actions/actions_simple.py
The current value of 200ms means chaining consistently doesn't work for me.  300ms seems to fix it consistently.
I could add a setting instead, but I still think 300ms is a better default, given it consistently breaks for me
=> Increase sleep for rename to allow chaining

packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts, packages/cursorless-engine/src/processTargets/marks/CursorStage.ts, packages/cursorless-engine/src/processTargets/marks/ImplicitStage.ts, packages/cursorless-engine/src/processTargets/marks/LineNumberStage.ts, packages/cursorless-engine/src/processTargets/marks/getActiveSelections.ts, packages/cursorless-engine/src/typings/Types.ts
- Depends on https://github.com/cursorless-dev/cursorless/pull/1472
=> Remove `currentSelections` and `currentEditor` from `ProcessedTargetsContext`

packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts, packages/cursorless-engine/src/languages/LanguageDefinitions.ts, packages/cursorless-engine/src/processTargets/ModifierStageFactoryImpl.ts, packages/cursorless-engine/src/processTargets/modifiers/ItemStage/ItemStage.ts, packages/cursorless-engine/src/processTargets/modifiers/ItemStage/getIterationScope.ts, packages/cursorless-engine/src/processTargets/modifiers/SurroundingPairStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeTypeStages/BoundedNonWhitespaceStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeTypeStages/ContainingSyntaxScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts, packages/cursorless-engine/src/typings/Types.ts
- Depends on https://github.com/cursorless-dev/cursorless/pull/1475
=> Remove `getNodeAtLocation` from `ProcessedTargetsContext`

packages/cursorless-engine/src/core/commandVersionUpgrades/canonicalizeAndValidateCommand.ts
`checkForOldInference` was returning a promise, but we weren't awaiting it, which is a smell imo.  This PR makes it clear that we don't wait for the user to respond to the inference warning
=> Make it clearer that we're not waiting for inference warning

packages/common/src/index.ts, packages/common/src/types/command/legacy/CommandV2.types.ts, packages/common/src/types/command/legacy/PartialTargetDescriptorV4.types.ts, packages/cursorless-engine/src/core/commandVersionUpgrades/upgradeV1ToV2/upgradeV1ToV2.ts, packages/cursorless-engine/src/core/commandVersionUpgrades/upgradeV3ToV4/upgradeV3ToV4.ts, packages/cursorless-vscode-e2e/src/suite/testCaseRecorder.test.ts
=> Clean up legacy types

packages/common/src/types/command/PartialTargetDescriptor.types.ts, packages/cursorless-engine/src/core/commandRunner/CommandRunnerImpl.ts, packages/cursorless-engine/src/core/handleHoistedModifiers.ts, packages/cursorless-engine/src/core/inferFullTargets.ts, packages/cursorless-engine/src/processTargets/MarkStageFactory.ts, packages/cursorless-engine/src/processTargets/MarkStageFactoryImpl.ts, packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts, packages/cursorless-engine/src/processTargets/marks/TargetMarkStage.ts, packages/cursorless-engine/src/runCommand.ts, packages/cursorless-engine/src/typings/TargetDescriptor.ts
- Generalize the way we handle scope hoisting in preparation for https://github.com/cursorless-dev/cursorless/pull/1497
- Depends on https://github.com/cursorless-dev/cursorless/pull/1494
=> Generalize "every" range hoisting code

cursorless-talon/src/actions/actions.py, cursorless-talon/src/actions/actions_simple.py, docs/user/README.md, packages/common/src/testUtil/TestCaseSnapshot.ts, packages/common/src/types/command/ActionCommand.ts, packages/cursorless-engine/src/actions/Actions.ts, packages/cursorless-engine/src/actions/SetInstanceReference.ts, packages/cursorless-engine/src/actions/actions.types.ts, packages/cursorless-engine/src/core/StoredTargets.ts, packages/cursorless-engine/src/core/commandRunner/CommandRunnerImpl.ts, packages/cursorless-engine/src/processTargets/ModifierStageFactoryImpl.ts, packages/cursorless-engine/src/processTargets/modifiers/InstanceStage.ts, packages/cursorless-engine/src/runCommand.ts, packages/cursorless-engine/src/testCaseRecorder/TestCase.ts, packages/cursorless-engine/src/testUtil/plainObjectToTarget.ts, packages/cursorless-engine/src/testUtil/takeSnapshot.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/clearEveryInstanceAir2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/clearEveryInstanceAir3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/clearFirstTwoInstancesAir2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/clearNextInstanceAir2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/clearNextInstanceAir3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/fromDrum.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/fromLine.yml, packages/cursorless-vscode-e2e/src/suite/recorded.test.ts
=> Support `"from"` action to set instance reference target

packages/cursorless-engine/src/languages/TreeSitterQuery/PredicateOperatorSchemaTypes.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/QueryCapture.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/QueryPredicateOperator.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/TreeSitterQuery.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/parsePredicates.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterIterationScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterTextFragmentScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/captureUtils.ts
This solution is simple and fairly clean, but there are a couple things I don't like about it:
I would prefer to have more separation between predicate operators, which just return `true` or `false`, and "mutator" operators that can alter the capture itself.  I started down that road, but decided it wasn't worth the complexity to create a whole other set of types for mutators
I don't love the idea of mutating your parameters; I prefer treating parameters as immutable and just returning an object indicating what should happen.  But that also would have made things a fair amount more complicated, and I don't imagine there will be a lot of these operators, so I don't think we need to come up with an airtight type system here.
=> Add mutable query capture interface

packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
- Fixes https://github.com/cursorless-dev/cursorless/issues/1482
- Depends on https://github.com/cursorless-dev/cursorless/pull/1501
=> Support `#start-position!` and `#end-position!` predicates

packages/cursorless-engine/src/languages/TreeSitterQuery/TreeSitterQuery.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/checkCaptureStartEnd.test.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/checkCaptureStartEnd.ts
=> Support for `@foo.start` and `@foo.end`

packages/cursorless-engine/src/languages/TreeSitterQuery/operatorArgumentSchemaTypes.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
- Depends on https://github.com/cursorless-dev/cursorless/pull/1505
- Fixes #1480
=> Support `#child-range!` predicate

packages/cursorless-engine/src/processTargets/modifiers/ContainingScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/RelativeExclusiveScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/RelativeInclusiveScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/constructScopeRangeTarget.ts, packages/cursorless-engine/src/processTargets/modifiers/getContainingScopeTarget.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BaseScopeHandler.test.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/CharacterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/DocumentScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/IdentifierScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/LineScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/ParagraphScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TokenScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterIterationScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterTextFragmentScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/mergeAdjacentBy.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/WordScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/scope.types.ts, packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts
- Depends on https://github.com/cursorless-dev/cursorless/pull/1506
=> Support multiple targets per scope

packages/cursorless-engine/src/languages/TreeSitterQuery/QueryCapture.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/TreeSitterQuery.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/checkCaptureStartEnd.test.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterIterationScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterTextFragmentScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/captureUtils.ts
- Depends on https://github.com/cursorless-dev/cursorless/pull/1509
- Fixes #1481
=> Support `#allow-multiple!` predicate to enable multiple content ranges

packages/cursorless-engine/src/processTargets/targets/PlainTarget.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/instance/clearTwoInstancesFirstThreeCarsAir.yml
The problem was that constructing a character range inadvertently resulted in a target with `isToken = true`, because when we clone the anchor target to create the new range target, we forgot to include the `isToken = false`.
=> Fix `"instance first three chars"`

cursorless-talon/src/cheatsheet/sections/modifiers.py, packages/cheatsheet/src/lib/sampleSpokenFormInfos/defaults.json
This is how `"backward"` looks:
But `"forward"` didn't have the same special treatment:
This PR makes it look as follows:
I also updated the cheatsheet json that we use to generate the [generic cheatsheet](https://www.cursorless.org/cheatsheet) while I was here
=> Fix `"forward"` in cheatsheet

packages/cursorless-engine/tsconfig.json, packages/cursorless-vscode/tsconfig.json, packages/vscode-common/tsconfig.json
Our legacy tests currently run against VSCode 1.66.0:
https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/packages/test-harness/src/util/launchVscodeAndRunTests.ts#L37
However, we pull in types for VSCode 1.61:
https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/packages/cursorless-vscode-core/package.json#L31
and the extension also declares support for the same version:
https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/packages/cursorless-vscode/package.json#L32
so 1.61 shall be our lowest common denominator.
VSCode 1.61.0 uses Electron 13: https://github.com/microsoft/vscode/blob/1.61.0/package.json#L134
Per [Electron's …
=> Bump engine/VSCode TypeScript target to ES2020

packages/cursorless-engine/src/core/commandRunner/selectionToStoredTarget.ts
Forgot to update doc string in previous pr
=> Updated doc string to be representative

packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
=> Fix `is-nth-child` predicate

docs/user/README.md
Add missing quote in ``"identifier`.  For the second one where I delete ` [blue] air and [green] bat`, at at first I thought it was just junk, but maybe you wanted to have a note about how it differs from the list item above.
=> fix README typos

packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts, packages/cursorless-engine/src/processTargets/targets/DocumentTarget.ts, packages/cursorless-engine/src/processTargets/targets/ImplicitTarget.ts, packages/cursorless-engine/src/processTargets/targets/InteriorTarget.ts, packages/cursorless-engine/src/processTargets/targets/LineTarget.ts, packages/cursorless-engine/src/processTargets/targets/NotebookCellTarget.ts, packages/cursorless-engine/src/processTargets/targets/ParagraphTarget.ts, packages/cursorless-engine/src/processTargets/targets/PlainTarget.ts, packages/cursorless-engine/src/processTargets/targets/PositionTarget.ts, packages/cursorless-engine/src/processTargets/targets/RawSelectionTarget.ts, packages/cursorless-engine/src/processTargets/targets/ScopeTypeTarget.ts, packages/cursorless-engine/src/processTargets/targets/SubTokenWordTarget.ts, packages/cursorless-engine/src/processTargets/targets/SurroundingPairTarget.ts, packages/cursorless-engine/src/processTargets/targets/TokenTarget.ts, packages/cursorless-engine/src/processTargets/targets/UntypedTarget.ts
https://github.com/cursorless-dev/cursorless/pull/1520#discussion_r1222855994
This adds a generic to `BaseTarget`, which is expected to receive the type of the subclass' parameters. This tries its best to enforce that is the case, and ensures implementations of `getCloneParameters` return that declared type.
=> Make BaseTarget parameters getters stricter

packages/cursorless-engine/src/core/Debug.ts
from
```
> source_file
> source_file
>> declarations
>> declarations
>>> settings_declaration
>>> settings_declaration
>>>> left: settings()
>>>> left: settings()
>>>> "settings()"
>>>> "settings()"
```
to
```
(source_file
(declarations
(settings_declaration
left: "settings()" @cursor
)
)
)
```
`console.debug` is the culprit in why we got to duplicated lines. Switching to `console.log` removes the duplicated lines. I think this is an improvement until we do #1115 
I'm not totally sure if I like the `@cursor`.
=>  Change debug log to represent tree sitter query syntax 

packages/cursorless-engine/src/processTargets/targetUtil/insertionRemovalBehaviors/TokenInsertionRemovalBehavior.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/rust/chuckFunkNameFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/rust/chuckName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/positions/chuckAir.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckBat.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken10.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken11.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken12.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken13.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken14.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken4.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken5.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken6.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken7.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken8.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/scopes/token/chuckToken9.yml
=> Make token removal range less aggressive

cursorless-snippets/functionDeclaration.cursorless-snippets, cursorless-snippets/ifElseStatement.cursorless-snippets, cursorless-snippets/ifStatement.cursorless-snippets
This brings Go support to all appropriate built-in cursorless snippets. Go is tantalizingly close to typescript, but just different enough to need its own bodies.
- [n/a] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [n/a] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [n/a] I have not broken the cheatsheet
=> Add Go support to snippets

cursorless-talon/src/marks/mark.py
=> Enable explicit gray color for default hats

packages/cursorless-vscode-e2e/src/suite/crossCellsSetSelection.vscode.test.ts, packages/cursorless-vscode-e2e/src/suite/editNewCell.vscode.test.ts, packages/cursorless-vscode-e2e/src/suite/intraCellSetSelection.vscode.test.ts, packages/cursorless-vscode-e2e/src/suite/skipIfWindowsCi.ts
Fixes #1260
I have now run the windows tests five times and everything appears to be working. If we run into any future problems this vscode command might be useful
`workbench.action.revertAndCloseActiveEditor`
=> Restore CI notebook tests on windows

packages/cursorless-engine/src/languages/markdown.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/bringItemDrumAfterBatt.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/chuckItem2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/clearItem2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/drinkItem.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/pourItem.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/pourItem2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/roundWrapItemAir.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/targets/scopeType/pourEntry.yml
Fixes #1200
Fixes #1199
Fixes #1107
=> Updated markdown item ranges

packages/cursorless-vscode-e2e/src/suite/crossCellsSetSelection.vscode.test.ts, packages/cursorless-vscode-e2e/src/suite/editNewCell.vscode.test.ts, packages/cursorless-vscode-e2e/src/suite/intraCellSetSelection.vscode.test.ts, packages/cursorless-vscode-e2e/src/suite/skipIfWindowsCi.ts
This reverts commit 34d56721a2b943360a441aeafbeeb03a7a2aed26 (#1581) because CI started failing.  See eg
- https://github.com/cursorless-dev/cursorless/actions/runs/5488035451/jobs/10000317419
- https://github.com/cursorless-dev/cursorless/actions/runs/5488386069/jobs/10001169135
=> Revert "Restore CI notebook tests on windows (#1581)"

packages/cursorless-engine/src/languages/typescript.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryItem.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearItem4.yml
=> Made jsx attributes be referable as item

packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTree/python/clearPair5.yml
=> Surrounding pairs: Fall back to text based algorithm when error node is detected.

packages/cheatsheet-local/package.json, packages/cheatsheet/package.json, packages/common/package.json, packages/cursorless-engine/package.json, packages/cursorless-org-docs/package.json, packages/cursorless-org/package.json, packages/cursorless-vscode-e2e/package.json, packages/cursorless-vscode/package.json, packages/meta-updater/package.json, packages/meta-updater/src/updatePackageJson.ts, packages/test-harness/package.json, packages/vscode-common/package.json
This is necessary to reset the ts cache; otherwise it will still think that the generated files are there and won't build them after we clean
=> Delete ts cache on clean

packages/cursorless-engine/src/typings/target.types.ts
=> Add comment explaining why we need `getRemovalHighlightRange`

packages/cursorless-engine/src/core/Debouncer.ts, packages/cursorless-engine/src/core/HatAllocator.ts
- Required by https://github.com/cursorless-dev/cursorless/pull/1651
=> Create `Debouncer`; use it for `HatAllocator`

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BaseScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/scopeHandler.types.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/shouldYieldScope.ts
- Required by https://github.com/cursorless-dev/cursorless/pull/1650
- Note that we have no tests here, but it is tested in https://github.com/cursorless-dev/cursorless/pull/1653
=> Add `includeDescendantScopes` field to scope handlers

packages/common/src/types/GeneralizedRange.ts, packages/common/src/types/generalizedRangeContains.test.ts, packages/common/src/types/generalizedRangeTouches.test.ts, packages/common/src/types/isGeneralizedRangeEqual.test.ts
- Required by https://github.com/cursorless-dev/cursorless/pull/1649
=> Add generalized range utility functions

packages/cursorless-vscode/src/constructTestHelpers.ts, packages/cursorless-vscode/src/extension.ts, packages/cursorless-vscode/src/vscodeApi.ts, packages/vscode-common/src/VscodeApi.ts, packages/vscode-common/src/getExtensionApi.ts, packages/vscode-common/src/index.ts
- Required by https://github.com/cursorless-dev/cursorless/pull/1649
=> Add `vscodeApi` for mocking

packages/cursorless-engine/src/ScopeVisualizer/ScopeRangeWatcher.ts, packages/cursorless-engine/src/api/ScopeProvider.ts, packages/cursorless-engine/src/cursorlessEngine.ts
- Depends on #1650 
- Depends on #1646 
- Required by #1653
=> Add `ScopeRangeWatcher`

packages/common/src/util/itertools.ts, packages/cursorless-engine/src/ScopeVisualizer/ScopeSupportChecker.ts, packages/cursorless-engine/src/api/ScopeProvider.ts, packages/cursorless-engine/src/cursorlessEngine.ts
- Required by #1653 
- Depends on https://github.com/cursorless-dev/cursorless/pull/1651
=> Add `ScopeSupportChecker`

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirToAfterBatVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirToBatVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirToBeforeBatVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirToEndOfBatVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirToStartOfBatVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/takeBatVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/takeFineVerticalPastBat.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/takeVerticalPastFine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/relativeScopes/clearOneLines.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/relativeScopes/clearOneToken.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/relativeScopes/clearOneTokens.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/subtoken/takeFirstPastSecondWordHarp.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/updateSelections/chuckFirstPastSecondCar.yml
=> Update spoken forms ad nauseam

packages/cursorless-engine/src/util/allocateHats/HatMetrics.ts
hatOldTokenRank decides which token, if any, to steal a hat from.
The goal is to steal a hat from the token that is least important.
As written, the code steals the hat from the token that is most important,
but only when there are no completely free hats available.
Fix that.
This does not happen often in practice.
This commit will have minimal impact on user experience.
The main benefit is avoiding future confusion over the code,
and being more robust if surrounding parts of the code change.
- [/] I …
=> fix inverted score in hatOldTokenRank

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/takeMap.yml
The existing code snippet is not valid Go code. This doesn't matter at the moment, but it will soon as we rework Go scopes. Fix it.
=> fix syntax in Go test

.eslintrc.json
Use [eslint-plugin-import's typescript config](https://github.com/import-js/eslint-plugin-import/blob/main/config/typescript.js) per [the recommendation in their readme](https://github.com/import-js/eslint-plugin-import#typescript).
=> eslint: Use import/typescript config

.pre-commit-config.yaml
Fixing copy-paste error that resulted in duplicate pre-commit test step name
=> Fix pre-commit step name

packages/cursorless-engine/src/languages/TreeSitterQuery/TreeSitterQuery.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/checkCaptureStartEnd.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/rewriteStartOfEndOf.test.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/rewriteStartOfEndOf.ts, queries/javascript.core.scm, queries/javascript.jsx.scm
This particular query pattern is going to be very common.
It's worth having syntactic sugar for.
In particular, this reduces the level of indentation
required to express that a node's associated scope
(iteration, trailing, leading, etc.)
should start or end at the start or end of a different node.
While we're here, make a related error message more helpful.
=> replace treesitter #start-position with .startof

.vscode/launch.json, cursorless-talon-dev/src/cursorless_test.talon, cursorless-talon-dev/src/spoken_form_test.py, cursorless-talon/src/actions/get_text.py, packages/cursorless-engine/src/test/fixtures/multiAction.fixture.ts, packages/cursorless-engine/src/test/fixtures/spokenFormTest.ts, packages/cursorless-engine/src/test/fixtures/synonymousSpokenForms.fixture.ts, packages/cursorless-engine/src/test/fixtures/talonApi.fixture.ts, packages/cursorless-engine/src/test/spokenForms.talon.test.ts
=> Add support for testing our Talon api; test "phones" and "format"

packages/cheatsheet/src/lib/components/CheatsheetLegendComponent.tsx, packages/cheatsheet/src/lib/components/CheatsheetListComponent.tsx, packages/cheatsheet/src/lib/components/CheatsheetNotesComponent.tsx
=> cheatsheet: Fix square corners extending past round corners

packages/cheatsheet/src/lib/sampleSpokenFormInfos/defaults.json
I confirmed they don't show up locally, so just need to remove them here
=> Remove positions from web cheatsheet

docs/user/README.md
- Fixes https://github.com/cursorless-dev/cursorless/issues/1537
=> add `"just"` section to reference page

data/playground/go/go.mod, data/playground/go/maps_and_lists.go, data/playground/go/statements.go, packages/cursorless-engine/src/languages/go.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListOne.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListOne2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListTrap.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListTrap2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListTrap3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListTrap4.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeListTwo.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeMapOne.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeMapOne2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeMapTrap.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeMapTrap2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeMapTrap3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/go/changeMapTrap4.yml, queries/go.scm
=> migrate Go scopes map and list to treesitter

pnpm-lock.yaml
#1745 is almost impossible to review :sweat_smile:
I'd suggest running `pnpm dedupe` on the PR but it turns out `main` has a whole bunch of duplicate transitive deps too, so running it against `main` first.
=> Run `pnpm dedupe`

package.json, packages/cursorless-org-docs/package.json, packages/cursorless-org-docs/tsconfig.json, packages/meta-updater/package.json, packages/meta-updater/src/updateTSConfig.ts, pnpm-lock.yaml
We have some security warnings on a couple packages that are dependencies of docusaurus, so I decided to upgrade to the latest to remove those dependencies. Docusaurus uses their nightly version on their own docs, and things seem to work for us on this version with no issue, so I think it's ok. In addition, we were violating their peer dependencies by using react 18; we now no longer need to do that.  Also, this version allows us to use mdx v2, which has a lot of niceties that we'll probably want as we do our big docs refactor (https://github.com/cursorless-dev/cursorless/issues/867)
- depends on https://github.com/cursorless-dev/cursorless/pull/1750 to fix typedoc failure
=> Bump docusaurus to `3.0.0-alpha.0`

packages/cursorless-engine/src/processTargets/ModifierStageFactoryImpl.ts, packages/cursorless-engine/src/processTargets/modifiers/ContainingScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/ItemStage/ItemStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeTypeStages/LegacyContainingSyntaxScopeStage.ts
=> Fix `"item"` fallback for next-gen scope handlers

cursorless-talon/src/cheatsheet/sections/special_marks.py
This got changed everywhere but here.
=> fix copy/paste error that breaks cheatsheet

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/talon/cloneCommand.yml, queries/talon.scm
=> Added insertion delimiter to Talon command

packages/cursorless-engine/src/languages/TreeSitterQuery/TreeSitterQuery.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts
- Fixes #1609
- Required by / tested by https://github.com/cursorless-dev/cursorless/pull/1448
=> Work around tree-sitter query search bug

packages/common/src/ide/types/FileSystem.types.ts, packages/common/src/index.ts, packages/cursorless-engine/src/cursorlessEngine.ts, packages/cursorless-vscode/src/extension.ts, packages/cursorless-vscode/src/ide/vscode/VscodeFileSystem.ts
- Required by https://github.com/cursorless-dev/cursorless/pull/1803
- Required by https://github.com/cursorless-dev/cursorless/pull/1663
=> Add generic file watcher api

packages/cursorless-engine/src/ScopeVisualizer/ScopeRangeWatcher.ts, packages/cursorless-engine/src/cursorlessEngine.ts, packages/cursorless-engine/src/languages/LanguageDefinition.ts, packages/cursorless-engine/src/languages/LanguageDefinitions.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts
- Depends on https://github.com/cursorless-dev/cursorless/pull/1802
=> Query hot reloading during development

cursorless-talon-dev/src/cursorless_test.talon, cursorless-talon/src/actions/actions.py, packages/cursorless-engine/src/test/fixtures/talonApi.fixture.ts
Fixes #1811
I have not added any Talon side tests. The reason for this is that the failing code path is not used with voice commands. You could only hit this bug by manually calling our public python api.
=> cursorless_command("replaceWithTarget") fix

packages/common/src/types/command/ActionDescriptor.ts, packages/cursorless-engine/src/actions/Actions.ts, packages/cursorless-engine/src/actions/GetTargets.ts, packages/cursorless-engine/src/generateSpokenForm/defaultSpokenForms/actions.ts, packages/cursorless-engine/src/generateSpokenForm/generateSpokenForm.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/getTargetsBatAndCap.yml
Fixes #1820
```talon
info <user.cursorless_target>:
target_info = user.private_cursorless_get_targets(cursorless_target)
print(target_info)
```
```python
def private_cursorless_get_targets(target: Any) -> list[dict]:
"""Get information about Cursorless target"""
return actions.user.private_cursorless_command_get(
{
"name": "private.getTargets",
"target": target,
}
)
```
```json
[
{"contentRange": {"start": {"line": 71, "character": 23}, "end": {"line": 71, "character": 53}}}
]
```
=> Added get targets action

packages/cursorless-engine/src/util/allocateHats/maxByFirstDiffering.test.ts, packages/cursorless-engine/src/util/allocateHats/maxByFirstDiffering.ts
This cuts the runtime for hat allocation
in my tests by about 20%.
No functional changes.
I have not added any tests, but I have confirmed
that there are no functional changes
using my not-yet-submitted hat golden tests.
Part of the reason that the hat golden tests are not
yet ready for review is that they are way too slow.
=> do a single pass in maxByFirstDiffering

.vscode/extensions.json
We added `ruff` in #1375. There's a corresponding VSCode extension by the author, so probably a good idea to use it to surface lints earlier than pre-commit.
https://github.com/astral-sh/ruff-vscode
=> vscode: Recommend ruff extension

packages/common/src/types/Position.ts, packages/common/src/types/Range.ts, packages/common/src/types/Selection.ts, packages/cursorless-engine/package.json, packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts, packages/cursorless-engine/src/util/setSelectionsAndFocusEditor.ts, packages/cursorless-engine/src/util/uniqDeep.ts, packages/cursorless-engine/src/util/uniqWithHash.test.ts, packages/cursorless-engine/src/util/uniqWithHash.ts, pnpm-lock.yaml
When given a comparator, uniqWith is quadratic.
Add uniqWithHash that uses an optional hash function
to return to approximately linear behavior,
assuming that the hash function is good.
For targets and selections,
Using the contentRange/selection as the hash value
seems to be pretty good in practice.
I've added "concise" printing versions of positions,
ranges, and selections. These are handy as hash functions,
but I've also made heavy use of them while investigating
hat allocation. They are generally useful.
"take every line" on a file containing 3000 lines
used to take about 15s on my computer.
Now it takes about 1s.
That's still not great but it's fast enough
that it doesn't appear that Cursorless has hung.
I've half a mind to try upstreaming this,
or at least sending a documentation …
=> implement non-quadratic version of uniqWith

packages/cursorless-engine/src/util/allocateHats/HatMetrics.ts
minimumTokenRankContainingGrapheme was accidentally
quadratic in the number of tokens sharing a grapheme.
It was executed for every token, and for each token,
it considered every single other token sharing a candidate grapheme.
It dominated hat allocation performance for larger numbers of tokens.
Memoizing the result by grapheme text makes it linear again.
No functional changes. (Confirmed by hat golden tests on another branch.)
=> memoize minimumTokenRankContainingGrapheme

packages/cursorless-engine/src/util/allocateHats/allocateHats.ts
Object.entries + map allocates a copy of the list twice.
And it ends up calling a tiny function over and over.
Using a boring nested for loop and an array
cuts hat allocation time by about 35%.
Removing items from an array one at a time is quadratic (triangular).
However, N is capped at the number of hats a user has (per grapheme),
which is fundamentally capped at a fairly small number.
And copying an array is typically a highly optimized operation.
This bit of hot code showed up in a profile from user saidelike on Slack.
I have tested that this does not modify behavior
on a branch with golden hat tests.
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) …
=> optimize getTokenRemainingHatCandidates

packages/cursorless-engine/src/languages/typescript.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeKey.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeKey2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeKey3.yml
=> Made interface names targetable as keys

data/playground/python/statements.py, data/playground/python/strings.py, packages/cursorless-engine/src/languages/getTextFragmentExtractor.ts, packages/cursorless-engine/src/languages/python.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/takeString2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/takeString3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/takeString4.yml, queries/python.scm
- Depends on #1863 
This PR also includes a few additional unit tests for Python strings.
=> Migrate Python to use next-gen scope handlers for text fragment extractors

packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
This has proved useful as I struggle with treesitter queries. :)
=> add #log! query predicate

packages/cursorless-engine/src/languages/TreeSitterQuery/checkCaptureStartEnd.ts
These used to print things like "[Object object]".
They are interface types, so we can't simply add a toString method.
=> improve treesitter query captureStartEnd error messages

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts
Suggested by some linter in GitHub Actions amidst a bunch of other scrollback.
=> cull dead code

packages/common/src/extensionDependencies.ts
`scalameta.metals` includes `scala-lang.scala` that actually adds the language identifier that we need. Switch to it directly to avoid installing more extensions than necessary
=> Switch scala dependency extension

cursorless-talon/src/marks/decorated_mark.py, cursorless-talon/src/marks/lines_number.py, cursorless-talon/src/marks/mark.py, cursorless-talon/src/marks/mark_types.py, cursorless-talon/src/marks/simple_mark.py, cursorless-talon/src/targets/target_types.py
This removes a bunch of `Any`s from the Talon code related to marks.
Ref: #725
=> Tighten Talon marks type hints

cursorless-talon/src/actions/actions.py, cursorless-talon/src/actions/get_text.py, cursorless-talon/src/actions/homophones.py
This fixes an incorrect type hint, removes a few implicit `Any`s, and tightens up how `cursorless_get_text_action` can be used.
=> Tighten and fix Talon actions type hints

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeState.yml, queries/python.scm
=> Made python match a cursorless statement scope

docs/user/README.md
It got orphaned from its parent in a recent commit
=> Fix "from" section in docs

docs/user/README.md
=> Fix delimiters typo

cursorless-talon/src/cheatsheet/sections/scopes.py
Fixes cheatsheet bug introduced in #1698 which only updated spoken form in defaults.json, which is used by cursorless.org/cheatsheet, but didn't update the code path that is used when user says "cursorless cheatsheet"
=> Fix `boundedNonWhitespaceSequence` in cheatsheet

packages/cursorless-engine/src/languages/python.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeEveryName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeEveryName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeEveryName3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeEveryType.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeEveryType2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeType.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeType2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/chuckName.yml, queries/python.scm
=> Migrate Python name and type scopes

.github/workflows/test.yml, .pre-commit-config.yaml, cursorless-talon-dev/src/default_vocabulary.py, packages/common/src/testUtil/TestCaseSnapshot.ts, packages/cursorless-engine/src/core/updateSelections/updateSelections.ts, packages/cursorless-engine/src/languages/clojure.ts, packages/cursorless-engine/src/processTargets/targets/ParagraphTarget.ts, packages/cursorless-vscode-e2e/src/suite/recorded.vscode.test.ts, packages/cursorless-vscode/src/ide/vscode/VscodeFocusEditor.ts, scripts/forbid-todo.sh
- Fixes https://github.com/cursorless-dev/cursorless/issues/1920
Here's a screenshot of a failed run:
=> Forbid TODOs in the codebase

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeName4.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeName5.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeValue4.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeValue5.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeValue3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/changeValue4.yml, queries/javascript.core.scm, queries/python.scm
- Depends on https://github.com/cursorless-dev/cursorless/pull/1922, which migrates `"name"` in Python
- Depends on #1924, which migrates `value` in Typescript
=> Support "name" and "value" in guard of Python for-each statements

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeNextValue.yml, queries/javascript.core.scm
We only want nested value scopes if there is more than one declarator in a statement.
Before:
After:
Unfortunately we have no good way to test this change until we have https://github.com/cursorless-dev/cursorless/issues/1524
**Edit**: I found a way to test it, but it's a bit hacky.
=> Fix value scope nesting in Typescript

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/changeEveryName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/changeName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/changeName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/changeName3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/chuckName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/chuckName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearEveryName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearEveryName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearEveryName3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName3.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName4.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName5.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName6.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/clearName7.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/drinkName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/pourName.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/pourName2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scm/takeName.yml, queries/scm.name.scm
Fixes https://github.com/cursorless-dev/cursorless/issues/1923
=> Include `@` in `name` for `scm` language

packages/cursorless-vscode/src/ide/vscode/VscodeConfiguration.ts, packages/cursorless-vscode/src/ide/vscode/hats/VscodeHatRenderer.ts
eg `"cursorless.private.hatShapesDir": "C:\\Users\\Andreas\\repositories\\pokey-dotfiles\\cursorless-hat-shapes",`
=> Added support for user home variable in settings

typings/object.d.ts
=> Add stronger typing for `Object.fromEntries`

packages/cursorless-vscode/src/ScopeVisualizerCommandApi.ts, packages/cursorless-vscode/src/extension.ts, packages/cursorless-vscode/src/registerCommands.ts
- Required by #1942 to be able to tell which scope is currently being visualized to highlight it in the sidebar
=> Expand scope visualizer api

packages/cursorless-vscode-e2e/package.json, packages/cursorless-vscode/package.json, packages/cursorless-vscode/src/ide/vscode/VscodeFileSystem.ts, packages/cursorless-vscode/src/ide/vscode/hats/VscodeHatRenderer.ts, packages/vscode-common/package.json, pnpm-lock.yaml
- Fixes https://github.com/cursorless-dev/cursorless/issues/1808
- Fixes https://github.com/cursorless-dev/cursorless/issues/1846
=> Switch file watcher to stop use polling; bump vscode to 1.66.0

pyproject.toml
Suppresses `Instance methods should take a "self" parameter` warnings in editors that use pyright (eg VSCode). Due to the way Talon defines action classes, these warnings are almost always noise in any Talon user file set
=> Don't report error for self parameter name

packages/cursorless-engine/src/core/commandVersionUpgrades/upgradeV1ToV2/upgradeStrictHere.ts
upgradeStrictHere.ts uses util.isDeepStrictEqual and using that version in the web version of Cursorless will be a hassle.  Use lodash.isEqual instead: ["Performs a deep comparison between two values to determine if they are equivalent."](https://lodash.com/docs#isEqual)
=> Switch from util.isDeepStrictEqual to lodash.isEqual.

packages/cheatsheet-local/package.json, packages/cheatsheet/package.json, pnpm-lock.yaml
- Addresses https://github.com/cursorless-dev/cursorless/security/dependabot/69
=> Bump jest to get newer `@babel/traverse`

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType9.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/chuckType5.yml, queries/typescript.core.scm
- Fixes https://github.com/cursorless-dev/cursorless/issues/1990
=> Support `as const` for `"type"`

packages/cursorless-engine/src/processTargets/modifiers/InstanceStage.ts, packages/cursorless-vscode-e2e/src/suite/instanceAcrossSplit.vscode.test.ts
It was incorrectly using the editor of the instance, rather than the "from" editor
=> Fix "from" / "instance" across splits

packages/cursorless-engine/src/snippets/snippet.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/snippets/ifWrapCap.yml
Support wrapping placeholders/numbered holes in snippets
=> Support wrapping snippet placeholders

packages/cursorless-engine/src/api/CursorlessEngineApi.ts, packages/cursorless-engine/src/cursorlessEngine.ts, packages/cursorless-engine/src/index.ts, packages/cursorless-engine/src/runCommand.ts, packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts, packages/cursorless-vscode/src/extension.ts
Use dependency injection for getting TestCaseRecorder into CursorlessEngine.
A future PR should perhaps move TestCaseRecorder into a new package, @cursorless/cursorless-dev or similar, to isolate developer-only dependencies that are needed in production code.
This is an alternate approach to https://github.com/cursorless-dev/cursorless/pull/2001 requested in a comment.
It is also the most TypeScript I've written to date, so I probably did some things stylistically wrong. Class `TestCaseRecorderCommandRunnerDecorator` in particular feels very C++-like, not very TS-like, to me.
=> Use dependency injection for TestCaseRecorder

packages/cursorless-org/package.json, pnpm-lock.yaml
ESLint and TypeScript should definitely not end up in the bundled output for the cursorless.org website.
=> cursorless-org: Move eslint/typescript to devDependencies

packages/cursorless-vscode/src/ide/vscode/hats/shapeAdjustments.ts
Since we updated our hat shapes I have been tweaking my own internal shape settings. 
=> Tweak hat sizes

packages/cheatsheet/package.json, pnpm-lock.yaml
`ts-jest` did not officially support TypeScript 5.x until `ts-jest@29.1`.
Also move `jest` to `devDependencies` whilst we're here.
=> cheatsheet: Update ts-jest to 29.1.1

packages/cursorless-engine/src/languages/getNodeMatcher.ts, packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/delimiterMaps.ts, packages/cursorless-engine/src/runIntegrationTests.ts, packages/cursorless-engine/src/scripts/transformRecordedTests/checkMarks.ts, packages/cursorless-engine/src/testCaseRecorder/TestCase.ts, packages/cursorless-engine/src/util/nodeMatchers.ts, packages/cursorless-engine/src/util/object.ts, packages/cursorless-vscode-e2e/src/suite/recorded.vscode.test.ts, typings/object.d.ts
=> Move custom Object.keys() overload to util

packages/common/src/ide/types/Configuration.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/LineScopeHandler.ts
`"cursorless.private.lineParagraphIterationScope": true,`
=> Added private setting to change line iteration scope to paragraph

package.json, packages/cursorless-org-docs/docusaurus.config.mts
And ensure linter is actually running on it
=> Cleanup docusaurus config

packages/common/scripts/my-ts-node.js
Attempt to fix failures like:
- https://github.com/cursorless-dev/cursorless/actions/runs/6864301970/job/18665758970
- https://github.com/cursorless-dev/cursorless/actions/runs/6852067329/job/18629742778
Seems like we weren't properly waiting for esbuild to complete or something; switching to using their node.js api, which is easier to read anyway
=> Attempt to fix my-ts-node flakiness

packages/common/scripts/my-ts-node.js
If two my-ts-node scripts run at same time there were bad races
=> Fix race conditions with my-ts-node.sh

packages/vscode-common/src/TestHelpers.ts, packages/vscode-common/src/getExtensionApi.ts, packages/vscode-common/src/index.ts
This makes it easier to excise the related test-specific code from the repo.
=> Move vscode-common's TestHelpers interface to its own file.

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType10.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType11.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType12.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType13.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType14.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType15.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType16.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType17.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType18.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType19.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType20.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearType.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearTypeNear.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearTypeNear2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearTypeUrge.yml, queries/typescript.core.scm
- fixes https://github.com/cursorless-dev/cursorless/issues/1231
=> Expand `"type"` to include generic type arguments / parameters

packages/cursorless-engine/src/languages/elseIfExtractor.ts, packages/cursorless-engine/src/processTargets/targets/DestinationImpl.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/rust/clearBranch5.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/rust/clearBranch6.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/rust/ditchBranch2.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearBranch4.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearBranch5.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/cloneBranch.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/ditchBranch.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/ditchBranch2.yml
`else if` is now part of the content range for the branch. 
Updated destination `constructChangeEdit` to support line this insertion delimiters with scopes where the content range doesn't take the full line. eg `} else if`
=> Updated content range for branch

changelog/2023-11-modalKeyboardVscodeCommands.md, docs/user/experimental/keyboard/modal.md, packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts, packages/cursorless-vscode/package.json, packages/cursorless-vscode/src/keyboard/KeyboardCommandsModal.ts, packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts, packages/cursorless-vscode/src/keyboard/defaultKeymaps.ts
=> Support mapping from key to VSCode command in Cursorless keyboard mode

packages/cursorless-engine/src/languages/getTextFragmentExtractor.ts, packages/cursorless-engine/src/languages/markdown.ts, queries/markdown.scm
=> Migrate markdown scopes

packages/common/src/testUtil/getFixturePaths.ts
Can now on windows use `/` in `testSubsetGrep.properties`
Fixes #1779
=> Support `/` on windows for fixtures grep

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeName6.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType21.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType22.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeType23.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/changeValue2.yml, queries/typescript.core.scm
Fixes #2072
Fixes #2083
Fixes #2033
=> Update typescript scopes

packages/common/src/ide/types/Configuration.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/LineScopeHandler.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyScope/changeEveryLine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/modifiers/everyScope/clearEveryLine.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/selectionTypes/takeEveryLine.yml
=> Make paragraph line iteration scope

package.json, packages/cursorless-org-docs/package.json, pnpm-lock.yaml
Removes dependency on wait-on, which has security warning
=> Bump docusaurus 3.0.0 => 3.0.1

packages/cursorless-engine/src/languages/python.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/chuckItem.yml
=> Added python import to collection item

packages/cursorless-vscode/src/ide/vscode/VscodeFocusEditor.ts
Partially addresses #1722
The problem is that when you focus the search editor focus is brought back to the import/query box. For now just don't focus the editor actually makes it so if the search editor is already in focus you can now use Cursorless in it. The simplest way to get to the search editor is probably use `search.action.focusNextSearchResult`. Unfortunately there is no command to focus the results generally. Focusing the next result we of course don't want to issue every time we do a Cursorless command.
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/ …
=> Don't focus search editor

packages/cursorless-vscode-e2e/src/suite/scopes.vscode.test.ts
=> Remove `.only` to reenable tests

.eslintrc.json, package.json, pnpm-lock.yaml
=> Disallow `.only` in mocha tests

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterScopeHandler.ts, queries/html.scm, queries/java.scm, queries/javascript.core.scm, queries/javascript.jsx.scm, queries/json.scm, queries/markdown.scm, queries/python.scm, queries/scm.scm, queries/talon.scm, queries/typescript.core.scm, queries/xml.scm, queries/yaml.scm
=> Terser leading/trailing syntax in scm

packages/cursorless-vscode/src/ide/vscode/notebook/notebookLegacy.ts
Once `isVscodeLegacyNotebookVersion` has determined that `getNotebookFromCellDocument` should call `getNotebookFromCellDocumentLegacy`, there is no need for `getNotebookFromCellDocumentLegacy` to determine that again, and doing so forces a cyclic import dependency.
=> Remove cyclic dependency between notebook.ts and notebookLegacy.ts.

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/markdown/changeEveryItem.yml, queries/markdown.scm
=> Add iteration scope for markdown items

packages/common/src/scopeSupportFacets/getLanguageScopeSupport.ts, packages/common/src/scopeSupportFacets/json.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/json/comment.block.scope, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/json/comment.line.scope, queries/json.scm, queries/jsonc.scm
After bumping tree-sitter-json in https://github.com/cursorless-dev/vscode-parse-tree/commit/5920905dcd80f35da18d560e4e475ad2c3b71bd7, the tree-sitter-json parser now has proper support for comments
Fwiw, that version also includes proper jsonl support, so it's no longer a hack
=> Add proper jsonc comment support

images/hats/hole.svg
The repeated subpath was unclosed.
This was invisible in fill mode, but apparent when adding a stroke.
No visual changes.
=> images/hats: close subpath in hole.svg

packages/common/src/testUtil/TestCaseSnapshot.ts, packages/cursorless-engine/src/actions/Actions.ts, packages/cursorless-engine/src/actions/SetSpecialTarget.ts, packages/cursorless-engine/src/actions/actions.types.ts, packages/cursorless-engine/src/core/commandRunner/CommandRunnerImpl.ts, packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts, packages/cursorless-engine/src/testUtil/takeSnapshot.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/changeNextInstanceChar.yml, packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/fromThis.yml, packages/cursorless-vscode-e2e/src/suite/recorded.vscode.test.ts
=> No automatic token expansion for "from"; stored target cleanup

packages/cursorless-vscode/src/ide/vscode/hats/VscodeHatRenderer.ts, packages/cursorless-vscode/src/ide/vscode/hats/shapeAdjustments.ts
To use, add e.g. `-#aa10ff` after any color in settings to add `#aa10ff` as the stroke color.
For example, my `userColor2` is `#000000-#ffffff`, and my green is `#14ff07-#00a336`.
This is intentionally undocumented: It is a hidden feature for folks to play around with, but only if they are paying a lot of attention, at which point they will know that is not officially supported. :)
If we decide we like it, we can eventually see about documenting and testing and generally "unhiding" it.
- [-] I have not …
=> support hat strokes as a hidden feature

packages/cursorless-vscode/src/ide/vscode/hats/VscodeHatRenderer.ts
This is part of porting Cursorless to work in the web environment.
This is a re-roll of https://github.com/cursorless-dev/cursorless/pull/2153 which I messed up with bad git-fu.
=> Convert VscodeHatRendered to use vscode.workspace.fs

packages/cursorless-vscode/src/ide/vscode/hats/VscodeHatRenderer.ts
=> Remove unnecessary import of TextDecoder from util.

packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts, packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts
=> Don't clobber keyboard target after executing action

docs/user/experimental/keyboard/modal.md, packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts, packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
This broke when we reworked our keyboard actions setup. It's also not properly integrated with new keyboard parser. If we wanted to support special keys like `backspace` with our keyboard parser, we should define a VSCode command that sends a keyboard token to our parser, and map `backspace` to that
We also add `remove` to default config, and tweak some maps while we're there
=> Stop using `backspace` for `remove` action; tweak maps

packages/common/src/scopeSupportFacets/python.ts, packages/common/src/scopeSupportFacets/scopeSupportFacetInfos.ts, packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/python/value.yield.scope, queries/python.scm
=> Add support for `yield` statements for `"value"` in Python

packages/cursorless-engine/src/scopeProviders/getTargetRanges.ts, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/html/element.scope, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/javascript/element.scope, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/talon/command.scope, packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/textual/document.scope
=> Fix interior scope tests

docs/user/README.md
Related discussion: https://talonvoice.slack.com/archives/C026KPTJE6T/p1708813018817909
=> {grand, every} rephrasings for clarity and consistency

packages/common/src/index.ts, packages/common/src/types/Edit.ts, packages/common/src/types/TextEditor.ts, packages/cursorless-engine/src/actions/BreakLine.ts, packages/cursorless-engine/src/actions/JoinLines.ts, packages/cursorless-engine/src/actions/Wrap.ts, packages/cursorless-engine/src/core/updateSelections/RangeUpdater.ts, packages/cursorless-engine/src/core/updateSelections/updateSelections.ts, packages/cursorless-engine/src/typings/Types.ts, packages/cursorless-engine/src/util/performDocumentEdits.ts, packages/cursorless-vscode/src/ide/vscode/VscodeEdit.ts, packages/cursorless-vscode/src/ide/vscode/VscodeTextEditorImpl.ts
` 7189 passing (5m)` all tests passing.
Just marking it as a draft PR for now until I confirm from neovim side that this is good interface.
=> refactor: make the text editor edit() interface better for neovim

packages/cursorless-org/next.config.js
=> Fix hot reload for dependencies of cursorless-org

.github/DISCUSSION_TEMPLATE/architectural-decision-record.yml
This codifies our ADR template (#1210) using [GitHub discussion category forms](https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms).
Note that this changes the heading levels (they'll all be `h3` I think), which means the **Options considered** heading will no longer be a subheading of the **Context**. This is probably fine – a lot of the other Markdown ADR templates have this section at the same level anyway.
=> github: Create ADR discussion category form

packages/cursorless-engine/src/actions/InsertCopy.ts, packages/cursorless-engine/src/actions/Remove.ts
From debugging the vscode cursorless extension, it seems the selection is automatically updated by vscode itself when dealing with the "remove" action while calling editBuilder.delete() (TextEditorEdit). 
However it is not the case for neovim so it was using the old selection.
I fixed it so cursorless always enforce selection for that "remove" action. Tested on neovim and vscode.
=> enforce new selection for "remove" action

.github/workflows/forbid-todo.yml, .github/workflows/test.yml, scripts/forbid-todo.sh
=> Make `Forbid TODOs` check into its own CI step

packages/cursorless-vscode-e2e/src/suite/scopeProvider/assertCalledWithScopeInfo.ts, packages/cursorless-vscode-e2e/src/suite/scopeProvider/runCustomRegexScopeInfoTest.ts, packages/cursorless-vscode-e2e/src/suite/scopeProvider/runCustomSpokenFormScopeInfoTest.ts
Just tuned / cleaned up the sleeps for our custom spoken forms tests. Mac tests passed 3 times in a row, which seems unlikely by chance given current unreliability, so I'd be tempted to ship it. Tempted to mock filesystem to make it faster / more robust, but that's work, and gives us slightly less confidence
=> Attempt to make macOS CI more robust

cursorless-talon-dev/src/spoken_form_test.py, cursorless-talon/src/actions/actions.py, cursorless-talon/src/actions/bring_move.py, cursorless-talon/src/actions/call.py, cursorless-talon/src/actions/get_text.py, cursorless-talon/src/actions/homophones.py, cursorless-talon/src/actions/paste.py, cursorless-talon/src/actions/reformat.py, cursorless-talon/src/actions/swap.py, cursorless-talon/src/actions/wrap.py, cursorless-talon/src/apps/vscode_settings.py, cursorless-talon/src/cheatsheet/cheat_sheet.py, cursorless-talon/src/cheatsheet/get_list.py, cursorless-talon/src/command.py, cursorless-talon/src/csv_overrides.py, cursorless-talon/src/cursorless_command_server.py, cursorless-talon/src/modifiers/surrounding_pair.py, cursorless-talon/src/number_small.py, cursorless-talon/src/private_api/private_api.py, cursorless-talon/src/scope_visualizer.py, cursorless-talon/src/snippets.py, cursorless-talon/src/targets/target_types.py, cursorless-talon/src/terms.py, pyproject.toml
- Depends on https://github.com/cursorless-dev/cursorless/pull/2306
- Supercedes https://github.com/cursorless-dev/cursorless/pull/2267
This does add a lot of noise, and it can't be enforced in CI because Talon doesn't publish type stubs (that I know of), so I wonder whether it's worth it 🤔
=> Fix or suppress all Python type errors

data/fixtures/recorded/fallback/takeToken2.yml, packages/common/src/FakeCommandServerApi.ts, packages/common/src/types/CommandServerApi.ts, packages/common/src/types/TestCaseFixture.ts, packages/cursorless-engine/src/core/getCommandFallback.ts, packages/cursorless-engine/src/testCaseRecorder/TestCase.ts, packages/cursorless-vscode-e2e/src/endToEndTestSetup.ts, packages/cursorless-vscode-e2e/src/suite/recorded.vscode.test.ts
This was not caught by our tests because we mock away command server. Not sure how catch this sort of thing in our tests; it's one of the hazards of mocking
This PR introduces a more robust approach, where `undefined` means that we don't know which element is focused, either because there is no command server, or we have not been called by the command server
- See also https://github.com/pokey/command-server/pull/25
=> Fix keyboard broken by #2235

.vscode/extensions.json, data/fixtures/scopes/csharp/class.scope, packages/common/src/scopeSupportFacets/csharp.ts, packages/cursorless-engine/src/languages/csharp.ts, queries/csharp.scm
=> C#: Migrate class scope

changelog/2024-05-reformatPublicAPI.md, cursorless-talon/src/actions/reformat.py, cursorless-talon/src/cursorless.talon, docs/user/customization.md
=> Added reformat action to public api

data/fixtures/scopes/typescript.core/value.typeAlias.scope, data/fixtures/scopes/typescript.core/value.typeAlias2.scope, packages/common/src/scopeSupportFacets/scopeSupportFacetInfos.ts, packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts, packages/common/src/scopeSupportFacets/typescript.ts, queries/typescript.core.scm
I wouldn't say I feel super strongly, but it looked like "value" to my brain so I tried to use "value" here
=> typescript: Support "value" for type alias

packages/cursorless-engine/src/languages/clojure.ts, queries/clojure.scm
=> Clojure scope migration

packages/cursorless-engine/src/languages/scala.ts, queries/scala.scm
=> scala scope migration

data/fixtures/scopes/java/branch.if.iteration.scope, data/fixtures/scopes/java/branch.if.scope, data/fixtures/scopes/java/branch.try.iteration.scope, data/fixtures/scopes/java/branch.try.scope, packages/common/src/scopeSupportFacets/java.ts, packages/common/src/scopeSupportFacets/scopeSupportFacetInfos.ts, packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts, queries/java.scm
* Added branch scope for try catch statements in java
* Added missing iteration scope for if else branch in java
=> Added try branch for java

packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts, packages/cursorless-vscode/src/keyboard/TokenTypes.ts, packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts, packages/cursorless-vscode/src/keyboard/grammar/generated/grammar.ts, packages/cursorless-vscode/src/keyboard/grammar/grammar.ne, packages/cursorless-vscode/src/keyboard/grammar/grammar.test.ts, packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
- Fixes https://github.com/cursorless-dev/cursorless/issues/993
=> keyboard: Support "inside" and "bounds"

packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts, packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts, packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts, packages/cursorless-vscode/src/keyboard/grammar/generated/grammar.ts, packages/cursorless-vscode/src/keyboard/grammar/grammar.ne
- Fixes https://github.com/cursorless-dev/cursorless/issues/2412
=> keyboard: Add ability to make range past output of modifier

data/fixtures/recorded/implicitExpansion/clearBoundsToken.yml, data/fixtures/recorded/implicitExpansion/clearCoreToken.yml, data/fixtures/recorded/implicitExpansion/squareSwitchFunk.yml, data/fixtures/recorded/modifiers/changeBoundsValue.yml, data/fixtures/recorded/modifiers/changeInsideValue.yml, packages/cursorless-engine/src/actions/Rewrap.ts, packages/cursorless-engine/src/processTargets/modifiers/ConditionalModifierStages.ts, packages/cursorless-engine/src/processTargets/modifiers/InteriorStage.ts, packages/cursorless-engine/src/processTargets/modifiers/ItemStage/getIterationScope.ts, packages/cursorless-engine/src/processTargets/modifiers/commonContainingScopeIfUntypedModifiers.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeTypeStages/BoundedNonWhitespaceStage.ts, packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts, packages/cursorless-engine/src/processTargets/targets/DocumentTarget.ts, packages/cursorless-engine/src/processTargets/targets/ScopeTypeTarget.ts, packages/cursorless-engine/src/processTargets/targets/SurroundingPairTarget.ts, packages/cursorless-engine/src/scopeProviders/getTargetRanges.ts, packages/cursorless-engine/src/typings/target.types.ts
This one bit me a lot. See the test case for what now works. Basically "inside value" when value is a string is the most common one
=> Make "inside" fall back to pair when the target doesn't have an interior

packages/common/src/ide/normalized/NormalizedIDE.ts, packages/common/src/ide/types/Configuration.ts, packages/cursorless-engine/src/KeyboardTargetUpdater.ts, packages/cursorless-engine/src/cursorlessEngine.ts
- Fixes https://github.com/cursorless-dev/cursorless/issues/2421
This is experimental, and currently guarded by a hidden setting. To activate this behaviour, add the following to your vscode `settings.json`:
```json
"cursorless.experimental.keyboardTargetFollowsSelection": true,
```
Note that it is debounced, so the pink highlight will lag slightly. We could change that but I was worried it might slow down cursor movement
=> keyboard: Have keyboard target follow selection if it moves

packages/common/src/types/TextEditor.ts, packages/cursorless-engine/src/actions/CallbackAction.ts, packages/cursorless-vscode-e2e/src/suite/revealRange.vscode.test.ts, packages/cursorless-vscode/src/ide/vscode/VscodeTextEditorImpl.ts
Was removed by mistake in
https://github.com/cursorless-dev/cursorless/commit/008baa11ebcf5a9c1a08c7da8a10c544e2e84800
=> Reactivate reveal range on focus editor

docs/user/customization.md, packages/cursorless-vscode-e2e/src/suite/toggleDecorations.vscode.test.ts, packages/cursorless-vscode/src/ide/vscode/hats/VscodeHats.ts
```talon
hats on:  user.run_rpc_command("cursorless.toggleDecorations", true)
hats off: user.run_rpc_command("cursorless.toggleDecorations", false)
```
Fixes #2462
=> Allow toggle decorations to take a boolean argument

packages/cursorless-vscode/package.json, packages/cursorless-vscode/src/keyboard/KeyboardCommandsModal.ts, packages/cursorless-vscode/src/keyboard/KeyboardConfig.ts
Addresses https://github.com/cursorless-dev/cursorless/issues/2401, the ability to have custom cursor styling exclusively when in cursorless keyboard mode.
Tried to follow the repo style as best as possible but please let me know if another way besides a record mapper is more idiomatic for TS.
- _I could add docs in the visual a11y section but unclear if experimental keyboard support belongs there_
An image showing the cursor start out with a custom type, then change into `block` when keyboard mode is activated, thus adding more contrast.
=> Keyboard cursor customization

flake.nix
=> remove pre-commit install from nix dev shell (#2461)

data/fixtures/scopes/go/textFragment.comment.line.scope, data/fixtures/scopes/go/textFragment.string.multiLine.scope, data/fixtures/scopes/go/textFragment.string.singleLine.scope, packages/common/src/scopeSupportFacets/go.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts, queries/go.scm
When using these multiline strings in go
```
`foo`
```
we get a node of type `raw_string_literal` which have no children so the `child-range` predicate ran into an undefined at runtime problem.
Fixes #2458
=> Fix bug with go text fragment

packages/cursorless-engine/src/KeyboardTargetUpdater.ts, packages/cursorless-engine/src/processTargets/MarkStageFactoryImpl.ts, packages/cursorless-engine/src/processTargets/marks/CursorStage.ts
Before, if you have the new target follows cursor setting enabled, the "pour" action wouldn't do anything because it was a strong target. Changing it so it's equivalent to setting keyboard target to "this" every time you move cursor
Didn't add tests because this setting is still super experimental; not convinced we want to keep it
=> Fix "pour" / "drink" with keyboardTargetFollowsSelection

cursorless-talon/src/command.py
Latest pylance version is giving me the following error:
```
Cannot access attribute "__class__" for class "type[DataclassInstance]"
  A property defined within a protocol class cannot be accessed as a class variable
```
Note that this solution came from a chat with chatgpt so I have no idea whether it's correct. Please review carefully. We really should have unit tests for this function
I did run local talon tests and all green, as well as tried cheatsheet
=> Fix Python type error

packages/common/src/ide/types/RawTreeSitterQueryProvider.ts, packages/common/src/index.ts, packages/cursorless-engine/src/cursorlessEngine.ts, packages/cursorless-engine/src/disabledComponents/DisabledLanguageDefinitions.ts, packages/cursorless-engine/src/disabledComponents/DisabledTreeSitter.ts, packages/cursorless-engine/src/languages/LanguageDefinition.ts, packages/cursorless-engine/src/languages/LanguageDefinitions.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeTypeStages/LegacyContainingSyntaxScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts, packages/cursorless-vscode/src/extension.ts, packages/file-system-common/src/FileSystemLanguageDefinitionsProvider.ts, packages/file-system-common/src/index.ts
- [] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
=> Added Tree sitter provider

packages/cursorless-engine/src/runIntegrationTests.ts
Since `runIntegrationTests` is constructed in the engine it cannot use assert. Switching assert to throwing an error I think is totally fine here. It will still fail the test and we don't have that many legacy scopes left and hopefully soon they will be gone as well.
=> Remove node from runIntegrationTests

packages/cursorless-engine/src/core/HatTokenMapImpl.ts, packages/cursorless-engine/src/util/bigint.ts
Since we're using a threshold of sixty seconds I don't think we need nanosecond precision. Instead of finding a polyfill for bigint I just switch to date.now which gives us the time in milliseconds.
=> Remove node process from hat token map

packages/common/src/types/TalonSpokenForms.ts, packages/cursorless-engine/src/disabledComponents/DisabledTalonSpokenForms.ts, packages/cursorless-engine/src/spokenForms/CustomSpokenForms.ts
=> Added disabled spoken forms error

packages/test-harness/package.json
Not totally sure what it's about but this fix makes the warnings go away and doesn't break anything
```
▲ [WARNING] "./reporters/parallel-buffered" should be marked as external for use with "require.resolve" [require-resolve-not-external]
../../node_modules/.pnpm/mocha@10.3.0/node_modules/mocha/lib/nodejs/parallel-buffered-runner.js:19:2:
19 │   './reporters/parallel-buffered'
╵   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
▲ [WARNING] "./worker.js" should be marked as external for use with "require.resolve" [require-resolve-not-external]
../../node_modules/.pnpm/mocha@10.3.0/node_modules/mocha/lib/nodejs/buffered-worker-pool.js:16:36:
16 │ const WORKER_PATH = require.resolve('./worker.js');
╵                                     ~~~~~~~~~~~~~
```
- [-] I have added …
=> Fix esbuild warning

packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts, packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts
=> keyboard: Target selection after action, rather than "that"

.github/workflows/pre-commit.yml
To remove deprecation warning:
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-python@v4, actions/cache@v3, pre-commit-ci/lite-action@v1.0.1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
Eg in https://github.com/cursorless-dev/cursorless/actions/runs/9993881129
=> bump github action versions

packages/cheatsheet-local/tsconfig.json, packages/cheatsheet/tsconfig.json, packages/common/tsconfig.json, packages/cursorless-cheatsheet/tsconfig.json, packages/cursorless-engine/tsconfig.json, packages/cursorless-org-docs/tsconfig.json, packages/cursorless-org/tsconfig.json, packages/cursorless-vscode-e2e/tsconfig.json, packages/cursorless-vscode/tsconfig.json, packages/meta-updater/src/updateTSConfig.ts, packages/meta-updater/tsconfig.json, packages/node-common/tsconfig.json, packages/sentence-parser/tsconfig.json, packages/test-case-recorder/tsconfig.json, packages/test-harness/tsconfig.json, packages/vscode-common/tsconfig.json, tsconfig.base.json
This shipped in Typescript 5.5; see https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-configdir-template-variable-for-configuration-files
=> Use new `$configDir` setting in tsconfig

packages/cursorless-engine/src/actions/Sort.ts
`Intl.Collator` is not available in all environments. `localeCompare` gives the same result
=> Stop using Intl.Collator

.github/workflows/test.yml
This is a very minor tweak, but super useful for testing workflows. It allows you to trigger workflows manually via a github repo's actions tab, or even more useful is running the workflows on alternative branches via the command line. So for example if I am testing changes I've pushed to workflow in my own dev branch and want to quickly see if it works without having to send a PR or work on main branch to trigger, I can do something like this: `gh workflow run "Run Tests" --ref fix-lua-test-ci` and it will manually trigger the `Run Tests` workflow.
=> feat: add manual workflow dispatch

packages/cursorless-engine/src/actions/BreakLine.ts, packages/cursorless-engine/src/actions/BringMoveSwap.ts, packages/cursorless-engine/src/actions/CallbackAction.ts, packages/cursorless-engine/src/actions/EditNew/runEditTargets.ts, packages/cursorless-engine/src/actions/EditNew/runInsertLineAfterTargets.ts, packages/cursorless-engine/src/actions/InsertCopy.ts, packages/cursorless-engine/src/actions/InsertEmptyLines.ts, packages/cursorless-engine/src/actions/InsertSnippet.ts, packages/cursorless-engine/src/actions/JoinLines.ts, packages/cursorless-engine/src/actions/PasteFromClipboard.ts, packages/cursorless-engine/src/actions/Remove.ts, packages/cursorless-engine/src/actions/Replace.ts, packages/cursorless-engine/src/actions/Rewrap.ts, packages/cursorless-engine/src/actions/Wrap.ts, packages/cursorless-engine/src/actions/WrapWithSnippet.ts, packages/cursorless-engine/src/core/updateSelections/updateSelections.ts, packages/cursorless-vscode/src/ide/vscode/VscodeInsertSnippets.ts
This introduces a new interface to perform updates. The requirements I had was:
1. Support both selections and ranges
2. Support both edits and callback
3. Support setting range expansion behavior per range/selection
4. Support updating selection internally
What this pr doesn't try to do:
1. Improve the range updater logic
Example
```ts
const {
selections: [updatedContentSelections],
ranges: [updatedEditRanges]
} = await new EditsUpdater(rangeUpdater, editableEditor, edits)
.selections(contentSelections)
.ranges(editRanges, RangeExpansionBehavior.openOpen)
.updateEditorSelections()
.run();
```
1. Should updating editor selections be opt out instead?
1. Here I'm using two separate classes `EditsUpdater` and `CallbackUpdater`. I'm a bit tempted to just use a single class and a polymorphic …
=> New interface for performing edits and updating ranges

.eslintrc.json
I don't know why we have any warnings. We either care about something or we don't. If we care, it shouldn't be allowed in CI. I hate yellow squiggles
=> Switch all lint warnings to errors

scripts/deploy-cursorless-nvim.sh
Avoiding bad things happening if someone tries to run the deploy script manually
=> Make neovim deploy script robust to being run incorrectly

scripts/deploy-cursorless-nvim.sh
Looks like the new `.github` directory didn't deploy because we were relying on `*` shell expansion, which skips hidden dirs
=> Correctly copy hidden files and preserve attributes

data/fixtures/scopes/javascript.core/functionName2.scope, data/fixtures/scopes/javascript.core/functionName3.scope, queries/javascript.function.scm
Since `const funk = ()  => {}` works I assumed that a function in a map would be treated the same. 
=> Support funk name scope in map

packages/common/src/types/HatTokenMap.ts, packages/cursorless-engine/src/core/HatAllocator.ts, packages/cursorless-engine/src/core/HatTokenMapImpl.ts, packages/cursorless-engine/src/util/allocateHats/allocateHats.ts, packages/cursorless-engine/src/util/allocateHats/chooseTokenHat.ts, packages/cursorless-engine/src/util/allocateHats/getHatRankingContext.ts, packages/cursorless-engine/src/util/allocateHats/getRankedTokens.ts
=> Make hat forcing more aggressive

packages/cursorless-vscode/scripts/install-local.sh
This could probably use a test as well, but just putting this up as is for now as many running this stand-alone isn't actually intended/expected.
Fixes #2616
=> fix: make 'pnpm -F cursorless-vscode install-local' work again

packages/cursorless-tutorial/src/TutorialImpl.ts
This one is a bit hard to test, but basically if you change a spoken form while preconditions are not met, it will think that they are met
I'm not sure why the change spoken form code was triggering tbh, but that is a question for another day
=> tutorial: Fix bug with tutorial reparse

packages/cursorless-org-docs/src/docs/user/release-notes/0.29.0.md, packages/cursorless-vscode/package.json
=> Release 0.29.0

cursorless-talon/src/modifiers/surrounding_pair.py, packages/cursorless-org-docs/src/docs/user/README.md
These are now deprecated and now error out after https://github.com/cursorless-dev/cursorless/pull/2457. We missed this reference in the documentation.
Fixes #2625
=> Remove references to left and right in surrounding pair documentation

packages/cursorless-org-docs/config/algolia/crawler-settings.js
I've already applied this change to the production crawler. We'll remove this exclusion as part of https://github.com/cursorless-dev/cursorless/issues/1642
=> docs: Exclude language docs from crawler

cursorless-talon-dev/src/spoken_form_test.py
There is no way of telling if Talon currently is using the system default microphone. Every time I run the Talon grammar tests this setting changes and I have to manually reset it which is really annoying.
=> Added setting to restore system default microphone after Talon grammar tests

cursorless-talon/src/get_grapheme_spoken_form_entries.py, cursorless-talon/src/spoken_forms.py, cursorless-talon/src/spoken_scope_forms.py
=> Fixed bug where we tried to read missing custom regex list

packages/cursorless-org-docs/src/docs/user/README.md
`"short block"` is a live feature and is in the cheatsheet but not in the main reference page.
Sidenote: y'all open to the cheatsheet being more explanatory than simply "bounded paragraph"?  `"short paint"` has "Non whitespace sequence stopped by surrounding pair delimeters".  I'm thinking "block stopped by surrounding pair delimiters".  If yes, I can submit a PR for that.
=> add `"short block"` section to reference page

packages/cursorless-vscode-e2e/src/suite/scopeProvider/runCustomRegexScopeInfoTest.ts
Possible solution to https://github.com/cursorless-dev/cursorless/issues/2538
As of this writing this seems to be required for mac CI, but not other platforms
=> Try to fix CI flakiness by adding sleep in custom regex scope test

data/fixtures/recorded/modifiers/preferredScope/clearItem.yml, packages/cursorless-engine/src/processTargets/modifiers/PreferredScopeStage.ts
ContainingScopeStage have some logic around how to treat legacy scopes that we were missing from PreferredScopeStage. 
=> Use containing scope stage in preferred scope stage

cursorless-talon/src/cheatsheet/sections/scopes.py, packages/cursorless-org-docs/src/docs/user/README.md
=> Added cheatsheet description for short block

changelog/2024-08-boundedHeadTail.md, data/fixtures/recorded/headTail/changeHead.yml, data/fixtures/recorded/headTail/changeHead2.yml, data/fixtures/recorded/headTail/changeTail.yml, data/fixtures/recorded/headTail/changeTail2.yml, data/fixtures/recorded/headTail/clearHeadLine.yml, data/fixtures/recorded/headTail/clearTailLine.yml, packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts
If no scope is specified for head/tail instead of defaulting to just line we now use the smallest of line or surrounding pair interior. This means that `"take head"` would be bounded by the surrounding pair just like `"short paint"`. If there is no surrounding pair the line is used just like today. You can also override this behavior by specifying line. `"take head line"` would always use the line regardless if you are in a surrounding pair or not.
Fixes #2434
The issue mentions a tag for this. I guess since this change is fully extension side it would be a vscode setting, but in tempted to just have this be enabled by default since it's a really useful feature.
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and …
=> Change default head/tail scope to be line bounded by matching pairs

.gitignore, cursorless-talon/.gitignore
When this is synced to [`cursorless-talon`](https://github.com/cursorless-dev/cursorless-talon) the `.gitignore` in the monorepo doesn't apply so copy the `.DS_Store` ignore for those on macOS to prevent spurious `untracked content` messages in `git`.
I don't think the checklist below applies in this case.
=> Add `.DS_Store` to `.gitignore` for `cursorless-talon`

cursorless-talon/src/apps/vscode_settings.py
Today you get a `ValueError: max() arg is an empty sequence` message that is quite confusing.
=> Show better exception message when vscode settings json is not found

cursorless-talon/src/spoken_scope_forms.py, data/fixtures/recorded/surroundingPair/changeString.yml
I have a on purpose conflict where I have `string: doubleQuotes` pair and `string: string` scope. This allows me to do `string wrap` that will do double quotes, but `take string` should be all strings not just double quotes. This worked fine before the dfa optimization where we flattened the scope types in #2628
Just rearranging the lists so the one with scope types has higher priority than the list of wrappers fixes this. 
=> Changed order surrounding pair lists were combined for spoken scope forms

cursorless-talon/src/apps/vscode_settings.py, data/fixtures/recorded/headTail/changeTail3.yml, packages/common/src/types/command/PartialTargetDescriptor.types.ts, packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SurroundingPairScopeHandler/SurroundingPairInteriorScopeHandler.ts
`change tail` did the wrong thing in this case
```py
"""|foo
bar
"""
```
=> Don't use multiline pairs for head/tail modifier.

data/fixtures/scopes/csharp/functionName.method.iteration.class.scope, data/fixtures/scopes/csharp/namedFunction.method.iteration.class.scope, packages/common/src/scopeSupportFacets/csharp.ts, queries/csharp.scm
=> Added iteration scope for csharp functions

data/fixtures/recorded/languages/kotlin/changeCall5.yml, data/fixtures/recorded/languages/kotlin/changeValue13.yml, queries/kotlin.scm
=> Added tests for recently-fixed Kotlin functionality.

cursorless-talon/src/cheatsheet/sections/modifiers.py, packages/cheatsheet/src/lib/sampleSpokenFormInfos/defaults.json, packages/cursorless-org-docs/src/docs/user/README.md
=> Update head/tail docs with regards to surrounding pairs

data/fixtures/scopes/dart/class.scope, data/fixtures/scopes/dart/className.scope, data/playground/dart.dart, packages/common/src/scopeSupportFacets/dart.ts, queries/dart.scm
=> add dart class support

data/fixtures/scopes/rust/string.singleLine.scope, data/fixtures/scopes/rust/textFragment.string.singleLine.scope, packages/common/src/scopeSupportFacets/rust.ts, queries/rust.scm
=> Proper handing of raw strings in rust

cursorless-talon/src/modifiers/simple_scope_modifier.py
I got unreliable behavior when we didn't have a default value here. Turns out that if you don't have a default value `settings.get(id, default)` will not actually return none or your specified default value. It will return a `NoValueType` object and that is evaluated to true in the if statements so everybody probably has preferred scope on now. This might be a change to Talon because I can't believe we didn't catch this earlier.
=> Default value for preferred scope setting

cursorless-talon/src/modifiers/ordinal_scope.py
This capture was missing our Cursorless prefix 
=> Added Cursorless prefects to ordinal_or_last capture

packages/cursorless-engine/src/processTargets/modifiers/ContainingScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/PreferredScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/RelativeScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BoundedScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/NestedScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/OneOfScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/ScopeHandlerFactory.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/ScopeHandlerFactoryImpl.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SurroundingPairScopeHandler/SurroundingPairInteriorScopeHandler.ts, packages/cursorless-engine/src/scopeProviders/ScopeRangeProvider.ts, packages/cursorless-engine/src/scopeProviders/ScopeSupportChecker.ts
=> Assert creation of scope handlers

cursorless-talon/src/check_community_repo.py
Related #https://github.com/cursorless-dev/cursorless/issues/1953
=> Check for community installation

cursorless-talon/src/cursorless.talon, cursorless-talon/src/marks/lines_number.py, cursorless-talon/src/modifiers/ordinal_scope.py, cursorless-talon/src/modifiers/relative_scope.py, cursorless-talon/src/number_small.py
Community has had a good version of number_small for two years now.
Talon grammar tests passed
- / ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
=> Deprecate tag `user.cursorless_custom_number_small`

packages/cursorless-vscode-e2e/src/suite/scopeProvider/runCustomSpokenFormScopeInfoTest.ts
Errors like this
https://github.com/cursorless-dev/cursorless/actions/runs/12454094525/job/34764966216#step:10:8885
I ran the test three times and everything appears to be working now.
=> Increase sleep to fix mac breakages in ci tests

packages/cursorless-engine/src/actions/ExecuteCommand.ts
=> Add empty line in ExecuteCommand

packages/cursorless-vscode-e2e/src/suite/scopeProvider/runBasicScopeInfoTest.ts
With the new scope tree version this test broke. The iteration scope for functions is the entire program I guess it's reasonable that an empty document is still considered a function iteration scope
https://github.com/cursorless-dev/cursorless/blob/ec914cad1e4c73d67a9d31054573b12450d1b7cd/queries/javascript.function.scm#L162
=> Updates scope support test for new parse tree version

packages/cursorless-engine/src/languages/TreeSitterQuery/treeSitterQueryCache.ts
You can't compare position instances with `===`
=> Properly compare positions for cache validation

cursorless-talon/src/get_grapheme_spoken_form_entries.py
The uu module is deprecated and removed in python 3.13
Its use was a bug anyhow. Error is used in typescript and was accidentally used in python.
=> Remove dependency on deprecated uu module   

packages/cursorless-vscode-e2e/src/suite/performance.vscode.test.ts
With our latest performance updates there is a clear difference in performance between containing and relative scopes. To keep track of this I have added relative scopes to the performance tests. I also added a few tests for every scope.
=> Added performance test for `select previous scope`

packages/cursorless-engine/src/languages/LanguageDefinition.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/QueryCapture.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/TreeSitterQuery.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/normalizeCaptureName.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/parsePredicatesWithErrorHandling.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/positionToPoint.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/rewriteStartOfEndOf.ts
First, were checking the captures against the SCM files in production, which was an oversight - should only be happening in debugging.
Secondarily, the existing implementation multiple map and filters. This part of the code is very time sensitive and can run quite long for large files since we are iterating every capture in the entire file.
This implementation aims to reduce iteration steps
Fixes https://github.com/cursorless-dev/cursorless/issues/2656
=> Increase performance for Tree sitter matches

cursorless-talon/src/apps/vscode_settings.py, cursorless-talon/src/marks/decorated_mark.py
Today on main this exception is not caught and the Cursorless list containing all the scopes is not filled which means that Cursorless is not working if we can't find the vscode json config file.
=> Properly handle exception from missing vscode config json file

data/fixtures/recorded/languages/typescript/changeInside.yml, data/fixtures/scopes/typescript.core/disqualifyDelimiter.scope, packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts, packages/common/src/scopeSupportFacets/typescript.ts, queries/typescript.core.scm
Disqualified `=>` in typescript function type definitions to be used in a matching pair delimiter.
=> Disqualify arrow delimiter in function type

data/fixtures/scopes/javascriptreact/textFragment.element.scope, data/fixtures/scopes/javascriptreact/textFragment.element2.scope, packages/common/src/scopeSupportFacets/javascriptreact.ts, packages/common/src/scopeSupportFacets/languageScopeSupport.ts, packages/common/src/scopeSupportFacets/scopeSupportFacetInfos.ts, packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts, queries/javascript.jsx.scm
=> Don't break jsx element text fragments

cursorless-talon/README.md
Came up during https://github.com/cursorless-dev/cursorless/pull/2720; if you land on the README it doesn't actually tell you what to do.
=> README.md: actually link the instructions

packages/cursorless-org-docs/src/docs/user/experimental/snippets.md
=> Update documentation instructing the users to use community snippets

data/fixtures/recorded/languages/markdown/changeCell.yml, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/LineScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/NotebookCellApiScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/NotebookCellScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/ScopeHandlerFactoryImpl.ts
The latest update for the notebook cell handler broke cells in markdown.
Also implements notebook scope handler with a one of scope handler the same way we do for collection item. We can have both language specific implementations as well as the ide notebook api so this is a more proper implementation.
=> Fix for markdown cells

packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts
Today's implementation when you say something like `take every item` will show an error message `Couldn't find containing collectionItem.` even if it's the iteration scope that is missing. 
This change makes it so that we get the error message `Couldn't find containing iteration scope for collectionItem.` instead. This greatly helps us with diagnosing what actually went wrong.
For program languages were a scope is defined in Tree sitter the current error message makes little sense. You could use `take scope` and it works fine, but when you say `take every scope` you get an error message that there is no scope. Much better to actually show that this language is missing an iteration scope.
- [/] I …
=> Remove unnecessary catch which caused confusing error when iteration scopes were missing

data/fixtures/scopes/textual/collectionItem.textual15.scope, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/CollectionItemScopeHandler/CollectionItemTextualScopeHandler.ts
We didn't properly pop this stack of iteration states. This led to items being grouped incorrectly.
=> Fix bug with collection item scope

packages/common/src/types/Position.ts, packages/common/src/types/Range.ts, packages/common/src/types/Selection.ts, packages/common/src/types/position.test.ts, packages/common/src/types/range.test.ts, packages/common/src/types/selection.test.ts
The current concise function is 0-based,  but sometimes when doing debug prints it's easier to have the positions be 1-based to match vscode ui.
=> Added range concise one based function

packages/common/src/types/TextEditor.ts, packages/cursorless-engine/src/actions/SetSelection.ts, packages/cursorless-vscode/src/ide/vscode/VscodeTextEditorImpl.ts
In vscode if you click on a word with the mouse corresponding words are highlighted. When using cursorless to set selection this doesn't happen on main.
Fixes #2604
=> Highlight word when setting selection

cursorless-talon/src/cheatsheet/cheat_sheet.py
=> Added paired delimiter string to cheat sheet

cursorless-talon/src/targets/destination.py, packages/cursorless-org-docs/src/docs/user/customization.md
=> Remove deprecated destination grammar

packages/cursorless-engine/src/processTargets/modifiers/InstanceStage.ts, packages/cursorless-engine/src/processTargets/modifiers/OrdinalScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/RelativeScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/listUtils.ts, packages/cursorless-engine/src/processTargets/modifiers/relativeScopeLegacy.ts, packages/cursorless-engine/src/processTargets/modifiers/targetSequenceUtils.ts
`Scope index out of range` is a bit confusing. At least add the scope type and witch index to the error message. 
Fixes #1540
=> Improve out of range error

packages/cursorless-engine/src/languages/TreeSitterQuery/validateQueryCaptures.test.ts, packages/cursorless-engine/src/languages/TreeSitterQuery/validateQueryCaptures.ts, queries/kotlin.scm
=> Allow `"return@"` in Kotlin Tree sitter queries

cursorless-talon/src/apps/cursorless_vscode.py
File dialogs interfere with the command server keypress. Commands like `"paste to line"` just ends up with a timeout error in the talon log and nothing happens. 
I have been running with this in my own fork of cursorless Talon for a while to test it out and I'm happy with the result. 
=> Disable Cursorless for vscode file dialogs

data/fixtures/scopes/talon/name.field.scope, data/fixtures/scopes/talon/value.field.scope, packages/common/src/scopeSupportFacets/talon.ts, queries/talon.scm
=> Exclude binary operator from Talon name and value scopes

data/fixtures/recorded/languages/markdown/changePair.yml, packages/common/src/types/command/PartialTargetDescriptor.types.ts, packages/cursorless-engine/src/generateSpokenForm/defaultSpokenForms/surroundingPairsDelimiters.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SurroundingPairScopeHandler/delimiterMaps.ts, packages/cursorless-engine/src/spokenForms/defaultSpokenFormMapCore.ts
Triple backticks wasn't supported as a matching pair
=> Added triple backtics matching pair to markdown language

data/fixtures/recorded/languages/markdown/changeLeadingItem.yml, data/fixtures/recorded/languages/markdown/chuckItem4.yml, data/fixtures/recorded/languages/markdown/roundWrapItemAir.yml, data/fixtures/scopes/markdown/collectionItem.unenclosed.scope, packages/common/src/scopeSupportFacets/markdown.ts, queries/markdown.scm
=> Update ranges for markdown item

cursorless-talon/src/spoken_forms.json, data/fixtures/recorded/actions/flashToken.yml, packages/common/src/types/command/ActionDescriptor.ts, packages/cursorless-engine/src/CommandHistory.ts, packages/cursorless-engine/src/actions/Actions.ts, packages/cursorless-engine/src/actions/FlashTargets.ts, packages/cursorless-engine/src/spokenForms/defaultSpokenFormMapCore.ts
=> Flash targets action

data/fixtures/scopes/javascript.core/pairDelimiter.scope, packages/common/src/scopeSupportFacets/javascript.ts, queries/javascript.core.scm
=> Support tagged templates strings in JavaScript

packages/common/src/types/TextEditor.ts, packages/cursorless-engine/src/actions/ToggleBreakpoint.ts, packages/cursorless-everywhere-talon-core/src/ide/TalonJsEditor.ts, packages/cursorless-vscode/src/ide/vscode/VscodeTextEditorImpl.ts, packages/cursorless-vscode/src/ide/vscode/VscodeToggleBreakpoint.ts, packages/neovim-common/src/ide/neovim/NeovimTextEditorImpl.ts
We had a specific type for breakpoint descriptions which is more or less the same format as our generalized ranges that we use in other places. 
=> Use generalized ranges in breakpoint action

data/fixtures/recorded/everyScope/changeEveryTokenInside.yml, data/fixtures/recorded/everyScope/changeLastTokenInside.yml, packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts
=> Fix bug with `"every token inside"`

cursorless-talon/src/modifiers/simple_scope_modifier.py, data/fixtures/recorded/containingScope/changeGrandGrandState.yml, packages/cursorless-engine/src/generateSpokenForm/primitiveTargetToSpokenForm.ts, packages/cursorless-org-docs/src/docs/user/README.md
Allows you to say grand multiple times. eg `"take grand grand state"`
Fixes #2152
=> Support grand grand scope

packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
The match predicate is built into Tree sitter and our own code was actually never running
=> Remove our own implementation of the match predicate

data/fixtures/recorded/languages/clojure/chuckItemZip.yml, data/fixtures/recorded/languages/clojure/clearItemBat.yml, data/fixtures/recorded/languages/clojure/clearItemFine.yml, queries/clojure.scm
Fix some of the clojure collection item regression from #2683
Related #2723
=> Improve item collection definition for clojure

data/fixtures/recorded/implicitExpansion/bringAirToEndOfThis.yml, packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts
=> Properly expand to token when using `"end of this"`

packages/cursorless-engine/src/actions/BringMoveSwap.ts, packages/cursorless-engine/src/actions/CopyToClipboard.ts, packages/cursorless-engine/src/actions/CutToClipboard.ts, packages/cursorless-engine/src/actions/Highlight.ts, packages/cursorless-engine/src/actions/ToggleBreakpoint.ts, packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts, packages/cursorless-engine/src/processTargets/targets/BoundedParagraphTarget.ts, packages/cursorless-engine/src/processTargets/targets/LineTarget.ts, packages/cursorless-engine/src/processTargets/targets/ParagraphTarget.ts, packages/cursorless-engine/src/scopeProviders/getTargetRanges.ts, packages/cursorless-engine/src/typings/target.types.ts, packages/cursorless-engine/src/util/targetUtils.ts
=> Changed getRemovalHighlightRange to return a GeneralizedRange

data/fixtures/scopes/typescript.core/name.variable.scope, queries/javascript.core.scm
=> Exclude parameterized from name scope

.github/workflows/test.yml
CI is broken for latest neovim version
Related #2793
=> Use a fixed neovim version

packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts, packages/cursorless-engine/src/processTargets/targets/DocumentTarget.ts
=> Clean up targets

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/CollectionItemScopeHandler/CollectionItemScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/NotebookCellScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/OneOfScopeHandler.ts
Passing in the scope type is only necessary if you're creating the scope handlers from that scope type. In the case where you're creating a one of handler from a list of scope handlers. Passing in the scope type as well just makes the code more verbose for no reason.
=> Clean up one of scope handler

packages/vscode-common/src/testUtil/openNewEditor.ts
=> Close sidebar when running vscode tests

cursorless-talon/src/actions/generate_snippet.py, packages/cursorless-vscode/src/migrateSnippets.ts, packages/cursorless-vscode/src/registerCommands.ts
1. Skip snippets with fields we cannot migrate instead of just discarding those fields
2. Show a untitled markdown document with the migration results
3. Use spoken forms/phrases from Talon
=> Migrate snippets follow up

data/fixtures/recorded/headTail/changeHead3.yml, packages/common/src/types/command/PartialTargetDescriptor.types.ts, packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BoundedScopeHandler.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SurroundingPairScopeHandler/SurroundingPairInteriorScopeHandler.ts, packages/cursorless-org-docs/src/docs/user/README.md
Today's implementation is too quirky with its single versus multiline behavior. I have multiple times gotten an unexpected behavior.
=> Change implementation of default bounded line for head/tail modifiers

.github/PULL_REQUEST_TEMPLATE.md
=> Removed checklist and added comment to pull request template

data/fixtures/recorded/actions/pourStateAirAndLineBat.yml, packages/cursorless-engine/src/actions/EditNew/EditNew.ts, packages/cursorless-engine/src/actions/EditNew/EditNew.types.ts, packages/cursorless-engine/src/actions/EditNew/runEditTargets.ts, packages/cursorless-engine/src/actions/EditNew/runInsertLineAfterTargets.ts
If you said `"pour state air and line bat"` where `air` was a multiline statement you got an undefined exception at runtime.
I have corrected the problem with our logic and also removed a not null assertion in favor of actually checking for null.
`"pour state air and line bat"` (if `air` was a multiline statement) now works instead of raising an exception.
=> Fixed bug with edit new

.github/workflows/deploy.yaml, .github/workflows/forbid-todo.yml, .github/workflows/pre-commit.yml, .github/workflows/test-docs.yml, .github/workflows/test.yml
* Added name to each work flow step
* Added padding between steps
Fixes #2796
=> Make work flow files more readable

.github/workflows/pr-description.yaml
GitHub includes the description comment when it formulates the commit message, which we don't want as it's pretty messy. We will ask users to remove the comment but we need to validate it before allowing merging.
Stolen from https://github.com/orgs/community/discussions/84771#discussioncomment-8039595.
=> Actions: attempt to validate PR description tests

.gitignore, .vscode/launch.json, packages/test-harness/src/runAllTests.ts, packages/test-harness/src/testSubset.ts
The issue suggested showing a pop-up, but this wasn't optimal. It was either blocking the tests from terminating or it closed immediately by itself. I also don't want to clobber the clipboard all the time.
Let's log to a file because it seems like the best of the options.
Fixes #2805
=> Log fail test to file went running tests locally

cursorless-talon/src/snippets_deprecated.py
This list was accidentally dropped. It's deprecated, but it's still needed for now.
=> Re-add deprecated wrapper snippet lists

cursorless-talon/src/spoken_forms.json
Use `snip` as the spoken form for snippets 
Cursorless now uses `"snip"` just like community to insert a snippet.
=> Use `snip` as the spoken form for snippets

cursorless-talon/src/snippets/snippets.py
Right now we are trying to use Cursorless to insert snippets no matter if we are actually in vscode or not
=> Only context override snippet insertion when Cursorless tag is active

cursorless-talon/src/csv_overrides.py, cursorless-talon/src/spoken_forms.json, cursorless-talon/src/spoken_forms.py
Read from deprecated snippet csv files if the exists, but do not create them if they don't.
Fixes #2841
=> Remove snippets from spoken form json

packages/test-harness/src/runAllTests.ts
I got tricked by `failedTests.properties` not updating when tests were successful.
=> Update `failedTests.properties` on success

.github/workflows/deploy.yaml, .github/workflows/test.yml
Currently this action is failing in ci.
https://github.com/cursorless-dev/cursorless/actions/runs/13525259964/job/37794066786#step:21:34
Hopefully updating to the latest version will fix this.
=> Update HaaLeo/publish-vscode-extension action version

packages/cursorless-engine/src/core/getPreferredSnippet.ts
=> Make missing snippet message include languages

CLAUDE.md
We can ask claude to keep updating it as we make changes
=> Add initial CLAUDE.md

packages/cursorless-org-docs/src/docs/user/README.md
=> Remove take before/after examples from docs

data/fixtures/recorded/surroundingPair/changePair.yml, packages/cursorless-engine/src/languages/TreeSitterQuery/isContainedInErrorNode.ts
Today we discard parse tree nodes if any of the ancestral nodes has a error. That means that any of the ancestral nodes has a descendant that is an error node. That could be something a hundred lines below that isn't really relevant to the node we are evaluating. This updates changes so we only look at error nodes that are adjacent to our ascending path.
=> Don't discard nodes with non adjacent error siblings

pnpm-lock.yaml
Saw `Browserslist: caniuse-lite is outdated` message in a netlify deploy so figured I'd just run the update as it's easy. See https://github.com/browserslist/update-db#readme. I ran:
```
pnpm up -r caniuse-lite
pnpm up -w caniuse-lite
pnpm dedupe
```
=> Update browsers-list db

packages/cursorless-org-docs/src/css/custom.css, packages/cursorless-org-docs/src/docs/user/languages/components/ScopeSupport.tsx, packages/cursorless-org-docs/src/docs/user/languages/components/ScopeSupportForLevel.tsx
=> Fix docs card for dark mode

packages/test-harness/src/launchVscodeAndRunTests.ts
We had already pinned the version for mac and Linux: https://github.com/cursorless-dev/cursorless/issues/2878 but it appears that we have the same problem on windows its just crashing with error code 0 which means our test runner wasn't signalling the failure.
Test run crashes on windows with false negative.
https://github.com/cursorless-dev/cursorless/actions/runs/14509376075/job/40704611423?pr=2893
It appears that it's `vscode.window.showTextDocument` in our `openNewEditor` utility that causes this. It's not always on the same test case. By default it crashes in the scope tests, but if I disable the scope test the same error occurs in our recorded tests that of course uses the same `openNewEditor` function. I can't recreate this locally. Looks like a memory leak or similar.
=> Pin vscode version in CI for windows

data/fixtures/recorded/everyScope/takeEveryToken.yml, packages/cursorless-engine/src/actions/snippetsLegacy/snippet.ts, packages/cursorless-engine/src/processTargets/PipelineStages.types.ts, packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts, packages/cursorless-engine/src/processTargets/modifiers/CascadingStage.ts, packages/cursorless-engine/src/processTargets/modifiers/ConditionalModifierStages.ts, packages/cursorless-engine/src/processTargets/modifiers/ContainingScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts, packages/cursorless-engine/src/processTargets/modifiers/InstanceStage.ts, packages/cursorless-engine/src/processTargets/modifiers/InteriorStage.ts, packages/cursorless-engine/src/processTargets/modifiers/LeadingTrailingStages.ts, packages/cursorless-engine/src/processTargets/modifiers/OrdinalScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/PreferredScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/RangeModifierStage.ts, packages/cursorless-engine/src/processTargets/modifiers/RelativeScopeStage.ts, packages/cursorless-engine/src/processTargets/modifiers/relativeScopeLegacy.ts, packages/cursorless-engine/src/processTargets/modifiers/targetSequenceUtils.ts, packages/cursorless-engine/src/scopeProviders/getIterationScopeRanges.ts
Unfortunately became quite a lot of changes to pass the modifier options, but I think this is the only way. It also opens up for more context aware modifiers in the future.
Fixes #2889
=> Don't discard everyScope selections for multiple targets

packages/cheatsheet/src/lib/sampleSpokenFormInfos/defaults.json, packages/cursorless-org-docs/src/docs/contributing/CONTRIBUTING.md
=> Update default cheatsheet

data/fixtures/recorded/positions/bringHarpToAfterFile.yml, data/fixtures/recorded/positions/bringWhaleToBeforeFile.yml, data/fixtures/recorded/selectionTypes/bringHarpToAfterFile.yml, data/fixtures/recorded/selectionTypes/bringWhaleToBeforeFile.yml, data/fixtures/scopes/textual/document.scope, packages/cursorless-engine/src/processTargets/targets/DocumentTarget.ts
Got tired of how often I need to say `"pour file slap"`. Also that the document should have a smaller insertion delimiter compared to a function is bit weird.
=> Update insertion delimiter for document scope

cursorless-talon/src/csv_overrides.py, cursorless-talon/src/spoken_forms.py
=> Fix bug in csv check_for_duplicates

queries/r.scm
=> Fix bug wit R arguments and incidental multiple matches

data/fixtures/recorded/headTail/changeTail4.yml, packages/common/src/types/command/PartialTargetDescriptor.types.ts, packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts, packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SurroundingPairScopeHandler/InteriorScopeHandler.ts
The test failed before this fix
`(a)| b`
`"change tail"` and you expect `| b` but because the domain of the surrounding pair interior is the entire surrounding pair you instead removed `)`. This fix requires strong containments on surrounding pair interiors.
=> Pass requireStrongContainment from head/tail modifier to interior scope handler

.prettierignore, packages/cursorless-org-docs/src/docs/contributing/CONTRIBUTING.mdx
Thanks to @auscompgeek for help with prettier
=> Remove contributing.mdx from prettierignore

data/fixtures/recorded/actions/bringName.yml, data/fixtures/recorded/hatTokenMap/bringPointAndHarpToEndOfThisAndEndOfWhaleTakeWhale.yml, packages/cursorless-engine/src/core/commandRunner/CommandRunnerImpl.ts, packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts
=> Allow duplicate targets for bring action
