src/constants.ts
src/test/suite/constants.test.ts
src/test/suite/fixtures/constants.fixture.ts

This allows matching subwords in all caps snake and kebab cases.
[Here's a demo of the regex.](https://regex101.com/r/lWanj2/2)
Closes #65

Fix subword for all caps tokens

---

CHANGELOG.md
src/Types.ts
src/inferFullTargets.ts
src/processTargets.ts
src/test/suite/fixtures/inferFullTargets.fixture.ts
src/test/suite/processTargets.test.ts

Final cleanup before new user release

---

src/actions/setSelection.ts

Fixed that on pre and post #82

---

src/inferFullTargets.ts
src/test/suite/inferFullTargets.test.ts

Infer missing end mark on ranges

---

src/Types.ts
src/processTargets.ts

Subtokens support reversed order ordinals

---

src/processTargets.ts

Fixed bug with two adjacent tokens

---

src/CalculateChanges.ts
src/CommandAction.ts
src/actions/BringMoveSwap.ts
src/actions/Paste.ts
src/actions/delete.ts
src/actions/wrap.ts
src/performDocumentEdits.ts

I gotta sign off for tonight but feel free to carry this one if you think they're nice abstractions
If you like it but won't have a chance I can try to pick it up tomorrow

A possible approach

---

src/Types.ts
src/processTargets.ts

`take tail air`
`chuck head bat`

Added modifiers head and tail

---

src/languages/python.ts
src/nodeSelectors.ts
src/test/suite/fixtures/recorded/languages/python/takeValueZero.yml

Fixed bug with array in pair value

---

package.json
src/test/runTest.ts

Tweak default colors

---

src/core/tokenizer.ts
src/test/suite/tokenizer.test.ts

Added support for unicode characters in regular expression

---

src/actions/Call.ts
src/test/suite/fixtures/recorded/actions/callFine.yml

Not sure why we were disallowing multiple destinations here

Support multiple destinations for call action

---

src/test/suite/recorded.test.ts

Workaround to improve CI stability

Increase number of test retries

---

src/processTargets/modifiers/surroundingPair/constants.ts
src/test/suite/fixtures/recorded/surroundingPair/parseTree/typescript/clearPair8.yml

Fix typescript angle bracket pair

---

src/processTargets/modifiers/surroundingPair/delimiterMaps.ts
src/test/suite/fixtures/recorded/surroundingPair/textual/clearEscapedSquare.yml
src/test/suite/fixtures/recorded/surroundingPair/textual/clearPair15.yml
src/test/suite/fixtures/recorded/surroundingPair/textual/clearPair16.yml
src/test/suite/fixtures/recorded/surroundingPair/textual/clearSquare.yml
src/typings/Types.ts

See also https://github.com/pokey/cursorless-talon/pull/139

Escaped square

---

src/languages/html.ts
src/test/suite/fixtures/recorded/surroundingPair/html/clearCurly.yml
src/test/suite/fixtures/recorded/surroundingPair/html/clearRound.yml
src/test/suite/fixtures/recorded/surroundingPair/html/clearRound2.yml

This PR makes surrounding pairs work using the textual extractor within HTML raw text, including script and style tags.

Fix html text fragment types

---

README.md
package.json

Update description and keywords

---

src/core/tokenizer.ts
src/test/suite/tokenizer.test.ts

Added block comments tokens to tokenizer

---

README.md

Remove line break because formatting on mobile was weird.  Here's what it looks like now:

Badge format tweak

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/new_programming_language.md
docs/contributing/adding-a-new-language.md

Adds a pull request template for adding a new language and a default template

Pull request templates

---

.github/workflows/deploy.yaml
src/scripts/prepareForExtensionPublish.ts

Attempt to fix issues with previous attempt at continuous delivery

Continuous delivery take II

---

.github/workflows/deploy.yaml

Looks like we need to set a username and email for git before we can push

Attempt to fix subrepo push

---

.github/workflows/deploy.yaml

We first let git subrepo reconcile with cursorless-talon before doing the push

Another attempt to fix subrepo push

---

cursorless-talon/src/modifiers/containing_scope.py
cursorless-talon/src/vendor/jstyleson.py
src/processTargets/processSelectionType.ts
src/test/suite/fixtures/recorded/selectionTypes/chuckLinkMade.yml
src/test/suite/fixtures/recorded/selectionTypes/chuckLinkMadePastLinkAir.yml
src/test/suite/fixtures/recorded/selectionTypes/chuckLinkPit.yml
src/typings/Types.ts

Related to issue https://github.com/pokey/cursorless-vscode/issues/426
I wouldn't be surprised if you guys want me to take another approach and not touch the non-whitespace scope. I would be perfectly fine with that. I just wanted you guys to see the idea so we can have the debate before we decide.
I recommend you go through the commits one by one; that will tell the most coherent story.

Add url scope

---

cursorless-talon/src/cheatsheet/cheat_sheet.py
cursorless-talon/src/cheatsheet/get_list.py

Added support to split on dots in cheat sheet

---

src/languages/cpp.ts
src/languages/csharp.ts
src/languages/java.ts
src/languages/python.ts
src/languages/typescript.ts
src/test/suite/fixtures/recorded/languages/cpp/clearName.yml
src/test/suite/fixtures/recorded/languages/cpp/clearValue.yml
src/test/suite/fixtures/recorded/languages/csharp/clearName.yml
src/test/suite/fixtures/recorded/languages/csharp/clearName2.yml
src/test/suite/fixtures/recorded/languages/csharp/clearName3.yml
src/test/suite/fixtures/recorded/languages/csharp/clearValue.yml
src/test/suite/fixtures/recorded/languages/csharp/clearValue2.yml
src/test/suite/fixtures/recorded/languages/csharp/clearValue3.yml
src/test/suite/fixtures/recorded/languages/java/clearName.yml
src/test/suite/fixtures/recorded/languages/java/clearValue.yml
src/test/suite/fixtures/recorded/languages/python/clearName.yml
src/test/suite/fixtures/recorded/languages/python/clearValue3.yml
src/test/suite/fixtures/recorded/languages/typescript/clearName.yml
src/test/suite/fixtures/recorded/languages/typescript/clearValue.yml

Added proper support for += operator

---

.github/workflows/deploy.yaml

If this doesn't work, I'm bailing on the gpg signature thing; found another way to protect the branch anyways

Try to fix GPG signing key

---

cursorless-talon/src/actions/wrap.py

Whoops 😅.  We really need talon-side regression tests

Fix talon error

---

docs/user/README.md

Closes https://github.com/cursorless-dev/cursorless-vscode/issues/570

docs: document move

---

docs/user/installation.md

Use `.git` suffix on install instructions

---

src/languages/constants.ts
src/languages/getNodeMatcher.ts
src/languages/getTextFragmentExtractor.ts
src/languages/markdown.ts
src/test/suite/fixtures/recorded/languages/markdown/chuckItem.yml
src/test/suite/fixtures/recorded/languages/markdown/chuckName.yml
src/test/suite/fixtures/recorded/languages/markdown/clearComment.yml
src/test/suite/fixtures/recorded/languages/markdown/clearItem.yml
src/test/suite/fixtures/recorded/languages/markdown/clearList.yml

Support markdown scope types

---

docs/contributing/_api-index.md
website/docusaurus.config.js

Attempt to fix docs link

---

src/testUtil/TestCaseRecorder.ts
src/testUtil/takeSnapshot.ts

For use with video / tutorial recorder to take pre- and post-phrase snapshots

Add `cursorless.takeSnapshot` command

---

website/docusaurus.config.js

Set up Algolia doc search

---

docs/user/installation.md

Clarify install instructions

---

docs/contributing/CONTRIBUTING.md
docs/user/README.md

More docs improvements

---

docs/contributing/test-case-recorder.md

Added example of custom tests transformation

---

docs/user/README.md

Add link to list of supported languages to README

---

docs/contributing/CONTRIBUTING.md

Document extension prerequisites for local testing

---

docs/user/README.md

Clarify introduction in main user README

---

src/languages/typescript.ts
src/test/suite/fixtures/recorded/languages/typescript/changeName2.yml
src/test/suite/fixtures/recorded/languages/typescript/changeName3.yml
src/test/suite/fixtures/recorded/languages/typescript/changeName4.yml
src/test/suite/fixtures/recorded/languages/typescript/changeName5.yml

Closes #716
- [ x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)

typescript fix assignment expression name scope

---

src/actions/EditNew.ts

Apply PR feedback to cleanupEditNew

---

package.json

See: https://code.visualstudio.com/updates/v1_68#_sponsoring-extensions

Add sponsorship link to extension view

---

src/actions/BringMoveSwap.ts
src/test/suite/fixtures/recorded/decorations/moveLineAir.yml

Use removal highlight range instead of removal range

---

src/languages/java.ts
src/test/suite/fixtures/recorded/languages/java/clearValue2.yml
src/test/suite/fixtures/recorded/languages/java/clearValue3.yml
src/test/suite/fixtures/recorded/languages/java/takeValue2.yml

Enable java return value as scope type value

---

src/test/suite/withinCellSetSelection.test.ts
src/util/setSelectionsAndFocusEditor.ts

Notebook selections toggle cell focus

---

src/test/openNewEditor.ts
src/test/suite/recorded.test.ts

Fall back to creating a new editor if it can't be reused

---

.github/workflows/deploy.yaml

Attempt to fix nx CI

---

docs/user/README.md

New cursorless tutorial playlist

---

docs/user/README.md

Closes #706. Didn't touch the cheatsheet for now.
Maybe these special marks could belong in their own section somehow? I wasn't sure so I just tacked them onto the preexisting marks section.

Documentation for row, up, down

---

src/test/suite/recorded.test.ts

This PR adds support for the Update fixtures launch configuration to change an error test to a success test, and vice versa.  Also adds support for Update fixtures to change the error name

Improve snapshot update with expected-error tests

---

src/util/setSelectionsAndFocusEditor.ts

Fix focus editor in changes working tree

---

package.json

Fixes https://github.com/cursorless-dev/cursorless/issues/911
Must be released at the same time as https://github.com/cursorless-dev/vscode-parse-tree/pull/50

Prefer ui side

---

src/core/Decorations.ts
src/core/HatTokenMap.ts
src/core/IndividualHatMap.ts
src/core/commandVersionUpgrades/canonicalizeTargets.ts
src/core/getHatThemeColors.ts
src/core/hatStyles.ts
src/core/shapeAdjustments.ts
src/processTargets/modifiers/OrdinalRangeSubTokenStage.ts
src/processTargets/modifiers/subToken.ts
src/scripts/hatAdjustments/add.ts
src/scripts/hatAdjustments/average.ts
src/test/suite/subtoken.test.ts
src/typings/targetDescriptor.types.ts
src/util/addDecorationsToEditor.ts

Refactor to remove `constants.ts`

---

src/test/suite/fixtures/recorded/ordinalScopes/clearFirstPaint.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearFirstPaint2.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearFirstToken.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearFirstToken2.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearLastPaint.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearLastPaint2.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearLastToken.yml
src/test/suite/fixtures/recorded/ordinalScopes/clearLastToken2.yml

Adds a few tests following on #960

Add ordinal implicit range tests

---

cursorless-talon/src/marks/lines_number.py
src/test/suite/fixtures/recorded/selectionTypes/clearRowTwoPastFour.yml
src/test/suite/fixtures/recorded/selectionTypes/clearRowTwoUntilFour.yml

Added support for line number ranges

---

src/processTargets/modifiers/scopeTypeStages/RegexStage.ts
src/test/suite/fixtures/recorded/customRegex/clearWhite.yml

Support custom unicode regexes

---

.github/PULL_REQUEST_TEMPLATE.md

Add docs checkbox to PR template

---

data/playground/text.txt
data/playground/typescript.ts

Small playground improvements

---

package.json
src/test/suite/recorded.test.ts
yarn.lock

To make assertion failures a bit more readable

Switch to `chai` for assertions

---

src/core/commandVersionUpgrades/canonicalizeAndValidateCommand.ts

Tweak inference warning message

---

src/languages/typescript.ts
src/test/suite/fixtures/recorded/languages/typescript/clearPair.yml

Support matching pair inside jsx text nodes

---

src/processTargets/modifiers/scopeHandlers/scopeHandler.types.ts

Improve JSdocs

---

package.json
src/processTargets/modifiers/scopeHandlers/CharacterScopeHandler.ts
src/processTargets/modifiers/scopeHandlers/IdentifierScopeHandler.ts
src/processTargets/modifiers/scopeHandlers/NestedScopeHandler.ts
src/processTargets/modifiers/scopeHandlers/TokenScopeHandler.ts
src/processTargets/modifiers/scopeHandlers/WordScopeHandler.ts
src/util/regex.ts
yarn.lock

Switch `NestedScopeHandler` to generator

---

src/test/suite/fixtures/recorded/scopes/token/takeToken.yml
src/test/suite/fixtures/recorded/scopes/token/takeToken2.yml

Make sure that non-empty ranges are overlapping for containing scope

---

cursorless-talon/src/cheatsheet/sections/modifiers.py

Updated to correct name for forward backward modifier

---

.github/PULL_REQUEST_TEMPLATE.md

Add checkbox to PR template for checking cheatsheet

---

src/languages/java.ts
src/test/suite/fixtures/recorded/languages/java/clearState3.yml
src/test/suite/fixtures/recorded/languages/java/clearState4.yml
src/test/suite/fixtures/recorded/languages/java/clearState5.yml
src/test/suite/fixtures/recorded/languages/java/clearState6.yml
src/test/suite/fixtures/recorded/languages/java/clearState7.yml

Added fields and methods to java statement definition

---

src/processTargets/targets/ScopeTypeTarget.ts
src/test/suite/fixtures/recorded/targets/scopeType/pourIfState.yml

Updated If statement insertion delimiter

---

src/apps/cursorless-vscode-e2e/suite/recorded.test.ts
src/extension.ts
src/libs/common/ide/PassthroughIDEBase.ts
src/libs/common/ide/fake/FakeIDE.ts
src/libs/common/ide/normalized/.eslintrc.json
src/libs/common/ide/normalized/NormalizedIDE.ts
src/libs/common/ide/spy/SpyIDE.ts
src/libs/vscode-common/getExtensionApi.ts

Introduce `NormalizedIDE` and use it in development and test

---

docs/user/updating.md

Add instructions to restart Talon when updating cursorless-talon

---

docs/user/experimental/keyboard/modal.md

Tweak keyboard docs

---

docs/user/customization.md

Improve customization docs

---

docs/user/experimental/keyboard/modal.md
package.json

[keyboard] Add some missing scopes

---

docs/user/README.md

Add indent / dedent to docs

---

src/core/inferFullTargets.ts
src/test/suite/fixtures/recorded/inference/bringRowOneBeforeBatt.yml
src/test/suite/fixtures/recorded/inference/bringRowOnePastTwoBeforeBatt.yml

Infer line scope from line number marks

---

src/apps/cursorless-vscode-e2e/suite/wrapWithSnippetAcrossSplit.test.ts
src/ide/vscode/VscodeInsertSnippets.ts

Fix cross-split wrap with snippet

---

src/apps/cursorless-vscode-e2e/suite/editNewCell.test.ts

See eg https://github.com/cursorless-dev/cursorless/actions/runs/4185105474/jobs/7251680386

Tweak test timing to improve robustness

---

packages/cursorless-vscode-core/scripts/initLaunchSandbox.ts

Fix init launch sandbox script

---

docs/user/README.md

Added "clone" action to docs

---

packages/test-harness/src/util/launchVscodeAndRunTests.ts

- Eg https://github.com/cursorless-dev/cursorless/actions/runs/4479616153/jobs/7873791164
- Applying workaround proposed in https://github.com/microsoft/vscode/issues/130414#issuecomment-1026275162

Attempt to fix flakey windows tests in ci

---

.github/workflows/deploy.yaml

Fix deploy

---

.github/workflows/codeql.yml

Make CodeQL hack not skip `main`

---

docs/contributing/CONTRIBUTING.md

Added missing install to pnpm

---

packages/cursorless-org-docs/docusaurus.config.js

Fix edit button in docs

---

packages/test-harness/src/util/launchVscodeAndRunTests.ts

Another attempt to fix windows ci

---

cursorless-talon-dev/src/cursorless_dev.talon
packages/cursorless-engine/src/actions/GenerateSnippet/GenerateSnippet.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/snippets/testSnippetMakeLine.yml

Fix escaping in snippets

---

packages/cursorless-engine/src/processTargets/targets/ScopeTypeTarget.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourChapter.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourEnvironment.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourParagraph.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourPart.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourSection.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourSubparagraph.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourSubsection.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/latex/pourSubsubsection.yml

Add newline delimiters for latex scope types

---

packages/cursorless-engine/src/core/Debug.ts
packages/cursorless-engine/src/core/HatTokenMapImpl.ts
packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
packages/cursorless-engine/src/index.ts
packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts
packages/cursorless-engine/src/typings/Graph.ts
packages/cursorless-engine/src/typings/TreeSitter.ts
packages/cursorless-engine/src/util/graphFactories.ts
packages/cursorless-vscode/src/constructTestHelpers.ts
packages/cursorless-vscode/src/extension.ts

Remove from graph: debug, testCaseRecorder, getNodeAtLocation,hatTokenMap

---

package.json
pnpm-lock.yaml

Bump `pnpm`: 7.29.1 => 8.1.0

---

packages/cursorless-engine/src/actions/Actions.ts
packages/cursorless-engine/src/actions/Call.ts
packages/cursorless-engine/src/actions/Clear.ts
packages/cursorless-engine/src/actions/CutToClipboard.ts
packages/cursorless-engine/src/actions/EditNew/EditNew.ts
packages/cursorless-engine/src/actions/EditNew/runNotebookCellTargets.ts
packages/cursorless-engine/src/actions/Find.ts
packages/cursorless-engine/src/actions/FollowLink.ts
packages/cursorless-engine/src/actions/InsertSnippet.ts
packages/cursorless-engine/src/actions/PasteFromClipboard.ts
packages/cursorless-engine/src/actions/Sort.ts
packages/cursorless-engine/src/actions/index.ts
packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
packages/cursorless-engine/src/index.ts
packages/cursorless-engine/src/typings/Graph.ts
packages/cursorless-engine/src/util/graphFactories.ts
packages/cursorless-vscode/src/extension.ts

Remove `actions` from `graph`

---

packages/cursorless-vscode-e2e/src/suite/editNewCell.test.ts

Attempt to fix Mac CI failures

---

.pre-commit-config.yaml
cursorless-talon/src/actions/reformat.py
cursorless-talon/src/cheatsheet/cheat_sheet.py
cursorless-talon/src/cheatsheet/sections/modifiers.py
cursorless-talon/src/csv_overrides.py
pyproject.toml

https://github.com/charliermarsh/ruff

Switch from shed to ruff

---

packages/cursorless-vscode/src/extension.ts

Don't block extension activation on hat allocation

---

packages/common/src/types/HatTokenMap.ts
packages/cursorless-engine/src/actions/Actions.ts
packages/cursorless-engine/src/actions/actions.types.ts
packages/cursorless-engine/src/core/Debug.ts
packages/cursorless-engine/src/core/HatTokenMapImpl.ts
packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts
packages/cursorless-vscode/src/extension.ts

Minor graph cleanup

---

packages/cursorless-engine/src/actions/Actions.ts
packages/cursorless-engine/src/actions/InsertSnippet.ts
packages/cursorless-engine/src/actions/WrapWithSnippet.ts
packages/cursorless-engine/src/core/Snippets.ts
packages/cursorless-engine/src/index.ts
packages/cursorless-engine/src/typings/Graph.ts
packages/cursorless-engine/src/util/graphFactories.ts
packages/cursorless-vscode/src/extension.ts

Seeing odd failures on #1386; seeing if a fresh branch fixes it.  It did last time we saw failures like that

Remove snippets from graph

---

.github/workflows/deploy.yaml
.github/workflows/test-docs.yml
.github/workflows/test.yml

See https://github.com/pnpm/action-setup#version

Use pnpm version from package.json

---

docs/user/README.md

Add documentation for `"phones"`

---

docs/user/README.md

Fix spoken form in readme

---

packages/cursorless-vscode/scripts/uninstall-local.sh

Improve uninstall-local script; show restart instruction

---

packages/cursorless-vscode/scripts/install-local.sh

No longer necessary as of #1379

Remove `--allow-star-activation`

---

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts

Add optimisations enabled by `allowAdjacentScopes`

---

packages/cursorless-engine/src/core/inferFullTargets.ts
packages/cursorless-engine/src/processTargets/TargetPipeline.ts
packages/cursorless-engine/src/typings/TargetDescriptor.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/bringAirAfterBatAndEveryTokenFinePastHarp.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLineEveryFunkAirPastBat.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLineFunkBlueAirAndCapPastBlueEach.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenBatAndFinePastGust.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenLineBatBetweenLook.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearSecondTokenEveryLineCapPastBlueFine.yml

More powerful "every line air past bat"

---

docs/contributing/CONTRIBUTING.md

Use proper code blocks to get copy button for necessary commands

---

packages/cursorless-vscode/package.json
pnpm-lock.yaml

Fixes `X [ERROR] Could not resolve "semver"`

Added missing semver dependency

---

packages/common/src/types/TestCaseFixture.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/transformations/identity.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/transformations/reorderFields.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/transformations/upgrade.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/types.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/upgradeDecorations.ts
packages/cursorless-engine/src/testCaseRecorder/TestCase.ts
packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts
packages/cursorless-engine/src/testUtil/cleanUpTestCaseCommand.ts
packages/cursorless-vscode-e2e/src/suite/recorded.test.ts

Clean up test case fixture types

---

.pre-commit-config.yaml
packages/cursorless-engine/src/scripts/transformRecordedTests/checkMarks.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/index.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/transformFile.ts
packages/cursorless-engine/src/testUtil/extractTargetKeys.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLineAirBetweenHarp.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLineAirPastDrum.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLineAirUntilFine.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLineBlockBatPastFine.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryLinePastBlockFine.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenBatBetweenEach.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenBatPastDrum.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenBatSkipPastEach.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenBatUntilEach.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/clearEveryTokenPastDrum.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/everyRange/preEveryTokenPastBat.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTreeParity/clearBoundsDouble.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTreeParity/clearBoundsDouble2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTreeParity/clearOutsideLeper.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTreeParity/clearOutsideRack.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTreeParity/clearRoundLeper.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTreeParity/clearRoundRepper.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/textual/clearBoundsDouble2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/textual/clearOutsideLeper.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/textual/clearOutsideRack.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/textual/takeRoundLeper.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/textual/takeRoundRepper.yml

Ensure that all marks are captured in recorded tests

---

packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts
packages/cursorless-engine/src/processTargets/index.ts
packages/cursorless-engine/src/processTargets/marks/RangeMarkStage.ts
packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts
packages/cursorless-engine/src/processTargets/modifiers/RangeModifierStage.ts
packages/cursorless-engine/src/typings/Types.ts
packages/cursorless-engine/src/util/unifyRanges.ts

Remove `actionFinalStages` and `actionPrePositionStages` from `ProcessedTargetsContext`

---

packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
packages/cursorless-engine/src/cursorlessEngine.ts
packages/cursorless-engine/src/processTargets/MarkStageFactoryImpl.ts
packages/cursorless-engine/src/processTargets/marks/DecoratedSymbolStage.ts
packages/cursorless-engine/src/typings/Types.ts

- Depends on https://github.com/cursorless-dev/cursorless/pull/1473

Remove `hatTokenMap` from `ProcessedTargetsContext`

---

packages/cursorless-engine/src/core/StoredTargets.ts
packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
packages/cursorless-engine/src/cursorlessEngine.ts
packages/cursorless-engine/src/processTargets/MarkStageFactoryImpl.ts
packages/cursorless-engine/src/processTargets/marks/StoredTargetStage.ts
packages/cursorless-engine/src/testCaseRecorder/TestCase.ts
packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts
packages/cursorless-engine/src/testUtil/takeSnapshot.ts
packages/cursorless-vscode-e2e/src/suite/recorded.test.ts
packages/cursorless-vscode/src/constructTestHelpers.ts
packages/cursorless-vscode/src/extension.ts
packages/vscode-common/src/getExtensionApi.ts

Merge stored targets into one `StoredTargetsMap`

---

packages/cursorless-engine/src/core/commandRunner/CommandRunner.ts
packages/cursorless-engine/src/cursorlessEngine.ts
packages/cursorless-engine/src/testCaseRecorder/TestCase.ts
packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts
packages/cursorless-engine/src/testUtil/extractTargetKeys.ts

Remove `TestCaseContext`

---

docs/user/README.md

fix instance typo

---

cursorless-talon/src/actions/find.py
cursorless-talon/src/actions/homophones.py
cursorless-talon/src/actions/reformat.py
cursorless-talon/src/actions/wrap.py
cursorless-talon/src/apps/cursorless_vscode.py

Rename incorrect usage of `targets`

---

packages/cursorless-engine/src/languages/LanguageDefinition.ts

- Depends on https://github.com/cursorless-dev/cursorless/pull/1504
- Fixes #1483

Support importing query files from other query files

---

packages/cursorless-engine/src/actions/PasteFromClipboard.ts
packages/cursorless-vscode/src/ide/vscode/VscodeTextEditorImpl.ts

Fix broken paste action

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunk.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunk2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunk3.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunk4.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunk5.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunk6.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunkName.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearEveryFunkName2.yml
queries/javascript.function.scm
queries/typescript.scm

Add iteration scope for typescript functions

---

packages/cursorless-vscode/package.json
packages/cursorless-vscode/src/scripts/preprocessSvgHats.ts
pnpm-lock.yaml

- Fixes https://github.com/cursorless-dev/cursorless/security/dependabot/53

Fix fast-xml-parser security vulnerability

---

packages/cursorless-engine/src/processTargets/modifiers/ItemStage/getIterationScope.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/chuckEveryItem.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem12.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem13.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem14.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem15.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem16.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem17.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem18.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/takeItem.yml

Fixing bugs on items scope

---

packages/cursorless-engine/src/processTargets/modifiers/ItemStage/tokenizeRange.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/clearItem19.yml

Better handling of escaped quotes in textual item

---

packages/cursorless-engine/src/processTargets/targets/SubTokenWordTarget.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/subtoken/chuckFinalTwoWords.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/subtoken/chuckFirstTwoWords.yml

Use correct delimited ranges for sub token words

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/subtoken/pourWord.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/subtoken/pourWordAir.yml

Added tests for pour word

---

docs/user/experimental/snippets.md

Remove old snippet instructions

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirBeforeBattAndAfterCap.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirBeforeBattAndAfterCapAndDrum.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/bringAirBeforeBattAndCap.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/takeStartOfAirAndBattAndEndOfCapAndDrum.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/takeStartOfBattAndEndOfBatt.yml

Added compound target position tests

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTree/python/clearQuad.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/surroundingPair/parseTree/python/clearTwin.yml

Added clear twin test

---

.github/PULL_REQUEST_TEMPLATE.md
.prettierignore

Really annoying that for each pr I have to makes space for an actual message

Added empty leading lines to pr template

---

packages/cursorless-engine/src/actions/BringMoveSwap.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/bringAirAfterAir.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/bringAirBeforeAir.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/bringAirToEndOfAir.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/bringAirToStartOfAir.yml

Changed expansion behavior for bring source targets to closedClosed

---

packages/cursorless-vscode/package.json
packages/meta-updater/src/updatePackageJson.ts

Remove `dist` during clean

---

packages/cursorless-engine/src/actions/InsertCopy.ts

Removed reveal line for insert copy action

---

packages/common/src/types/command/legacy/PartialTargetDescriptorV5.types.ts

Fix lint warnings for unused vars

---

cursorless-talon/src/csv_overrides.py
cursorless-talon/src/modifiers/scopes.py

And add notification for when we break it again

Remove ambiguous string scope

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/chuckStartOfBattPastEndOfFine.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/chuckStartOfBlockPastStartOfFile.yml

Added start of/end of range tests

---

packages/cursorless-vscode/src/ide/vscode/hats/VscodeHatRenderer.ts

If you increase your line height and increase Cursorless hat size, you may end up with hats that are wide enough to clip their neighboring hats.  This PR detects that situation and horizontally shrinks the hats so that they have a 1px margin from one another.  This does alter the aspect ratio of the hats, but if you've made them so big that they start clipping their nieghbors, I think this is the best solution.  If you don't want them to start deforming, make them smaller.  I don't really see any other option 🤔
Before:
After:

Make svg narrower if it will clip adjacent svgs

---

packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts

add a delete button to recorded testcase notifications

---

package.json
packages/cheatsheet-local/src/index.html
packages/cursorless-engine/src/actions/BringMoveSwap.ts
packages/cursorless-engine/src/actions/EditNew/EditNew.ts
packages/cursorless-engine/src/actions/PasteFromClipboard.ts
packages/cursorless-engine/src/core/HatAllocator.ts
packages/cursorless-engine/src/core/commandVersionUpgrades/canonicalizeAndValidateCommand.ts
packages/cursorless-engine/src/languages/TreeSitterQuery/checkCaptureStartEnd.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/TreeSitterScopeHandler.ts
packages/cursorless-org/src/styles/globals.css
packages/cursorless-vscode/src/ide/vscode/VscodeFlashHandler.ts
packages/cursorless-vscode/src/ide/vscode/VscodeFocusEditor.ts
pnpm-lock.yaml

https://prettier.io/blog/2023/07/05/3.0.0.html

Update to prettier 3.0.0

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/compoundTargets/chuckStartOfBattPastEndOfFine.yml

Remove one more `"batt"` spoken form

---

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/captureUtils.ts

Add a return type to captureUtils

---

packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/hatTokenMap/bringCommaToEndOfPointTakePoint.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/hatTokenMap/bringCommaToStartOfPointTakePoint.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/hatTokenMap/bringHarpToEndOfPointTakePoint.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/hatTokenMap/bringHarpToStartOfPointTakePoint.yml

Fix spoken forms for hat token map tests

---

packages/common/src/testUtil/serialize.ts

Remove remaining reference to `fullTargets`

---

docs/user/README.md

Remove reference to kebab

---

packages/common/src/index.ts
packages/common/src/testUtil/shouldUpdateFixtures.ts
packages/cursorless-vscode-e2e/src/endToEndTestSetup.ts
packages/cursorless-vscode-e2e/src/suite/recorded.vscode.test.ts

Move `shouldUpgradeFixtures` to common

---

packages/cursorless-engine/src/testCaseRecorder/TestCaseRecorder.ts

fix interpolation in logging strings

---

.vscode/launch.json

Fix and cleanup launch config

---

.vscode/settings.json

This is a replay of https://github.com/cursorless-dev/cursorless/pull/1680

remove overrides of file.exclude and search.exclude

---

cursorless-talon/src/spoken_forms.json
cursorless-talon/src/spoken_forms.py

Try to be fancy with csv

---

packages/cursorless-org-docs/package.json
pnpm-lock.yaml

Remove typedoc dependencies

---

package.json
packages/cheatsheet-local/package.json
packages/cheatsheet/package.json
packages/cursorless-org-docs/package.json
packages/cursorless-org/package.json
pnpm-lock.yaml

upgrade typescript to 5.1.6

---

package.json

bump pnpm to 8.6.12

---

packages/cheatsheet-local/package.json
pnpm-lock.yaml

Upgrade webpack

---

packages/cursorless-engine/src/core/inferFullTargetDescriptor.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/inference/bringAirToEndOfRowTwoAndRowThree.yml

Fixed bug with line number inference

---

.vscode/extensions.json
.vscode/settings.json
queries/javascript.core.scm
queries/ruby.scm
queries/typescript.scm

First pass of the new scm formatter. Looks reasonable to me.

Ran formatter on scm files

---

docs/user/README.md

#643, document `"give"`

---

package.json
pnpm-lock.yaml

deps: Upgrade `@pnpm/meta-updater` to 1.0.0

---

packages/cheatsheet/package.json
pnpm-lock.yaml

deps: upgrade jest-environment-jsdom

---

packages/common/package.json
packages/cursorless-engine/package.json
packages/cursorless-vscode-e2e/package.json
packages/cursorless-vscode/package.json
packages/test-harness/package.json
pnpm-lock.yaml

deps: Upgrade mocha to 10.2.0

---

cursorless-talon/src/cheatsheet/sections/actions.py
docs/user/README.md
packages/cheatsheet/src/lib/sampleSpokenFormInfos/defaults.json

doc `"drink"` and `"pour"` can do more than lines

---

.github/workflows/codeql.yml

Stop checking out repo in CodeQL merge queue hack

---

docs/user/glossary.md

Update docs on iteration range

---

cursorless-talon-dev/src/cursorless_test.talon
cursorless-talon/src/actions/actions.py
cursorless-talon/src/actions/homophones.py
cursorless-talon/src/actions/reformat.py
cursorless-talon/src/actions/replace.py
docs/user/customization.md
packages/cursorless-engine/src/test/fixtures/talonApi.fixture.ts

Added text insertion action to Cursorless public api

---

packages/cursorless-engine/src/languages/java.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/java/changeType.yml

Support generic scoped types for java

---

packages/cursorless-engine/src/actions/Replace.ts
packages/cursorless-engine/src/actions/Sort.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/placeHelloAfterAir.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/placeHelloToFine.yml

Updated source and that mark for replace action

---

cursorless-talon/src/cheatsheet/get_list.py

Type hint Talon cheatsheet get_list

---

.github/CODEOWNERS

Add Andreas to codeowners

---

packages/cursorless-engine/src/languages/TreeSitterQuery/QueryPredicateOperator.ts
packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
packages/cursorless-engine/src/languages/typescript.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeEveryValue.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeEveryValue2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeName.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeName2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeName3.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeValue.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeValue2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/changeValue3.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/chuckName.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/chuckName2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/chuckName3.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/chuckValue.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/javascript/chuckValue2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/jsx/changeEveryValue.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/jsx/changeEveryValue2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/jsx/chuckValue.yml
queries/javascript.core.scm
queries/javascript.jsx.scm

Migrate Typescript "value" to next gen; improve "name"

---

docs/user/customization.md

Clarify customization doc

---

package.json
packages/cursorless-org/package.json
pnpm-lock.yaml

Bump next.js to 13.5.4

---

docs/user/README.md

I saw this issue #1417 and thought that is something I can help add to the doc.  Hope this is what was intended and let me know if I'm doing something wrong.

Add "scout" and "scout all" to the docs

---

packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts
packages/cursorless-engine/src/processTargets/targets/ScopeTypeTarget.ts
packages/cursorless-engine/src/processTargets/targets/SubTokenWordTarget.ts
packages/cursorless-engine/src/processTargets/targets/UntypedTarget.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/cloneTwoArgs.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/itemTextual/cloneTwoItems.yml

- Fixes https://github.com/cursorless-dev/cursorless/issues/1691
- Fixes https://github.com/cursorless-dev/cursorless/issues/1959
- Also strengthens typing for clone args even more cc/ @auscompgeek

Fix "clone" action with `ScopeTypeTarget`

---

packages/cursorless-vscode/scripts/install-from-pr.sh

minor tweaks to install-from-pr

---

cursorless-talon/src/actions/actions.py

Fix custom actions in cheatsheet

---

cursorless-talon/src/csv_overrides.py
cursorless-talon/src/marks/decorated_mark.py
cursorless-talon/src/spoken_forms.py
cursorless-talon/src/spoken_forms_output.py

- This PR is the Talon side of #1940
- [-] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/) (will do in follow-up)

Write spokenForms.json from Talon

---

packages/cursorless-org/src/components/Layout.tsx

Fix horizontal divider on light

---

packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts
queries/talon.scm

See https://github.com/wenkokke/tree-sitter-talon/pull/42

Clean up talon.scm based on tree-sitter-talon 4.0

---

packages/cursorless-vscode/src/ScopeTreeProvider.ts

Fix tooltip on lang-specific scopes

---

package.json
pnpm-lock.yaml

Bump typescript-eslint to 6.10.0

---

packages/common/scripts/my-ts-node.js

Clean up my-ts-node.js

---

cursorless-talon/src/spoken_forms.py
packages/common/src/types/command/PartialTargetDescriptor.types.ts
packages/cursorless-engine/src/languages/cpp.ts
packages/cursorless-engine/src/languages/csharp.ts
packages/cursorless-engine/src/languages/java.ts
packages/cursorless-engine/src/languages/python.ts
packages/cursorless-engine/src/languages/rust.ts
packages/cursorless-engine/src/languages/scala.ts
packages/cursorless-engine/src/languages/typescript.ts
packages/cursorless-engine/src/scopeProviders/ScopeInfoProvider.ts
packages/cursorless-engine/src/scopeProviders/scopeTypeToString.ts
packages/cursorless-engine/src/spokenForms/defaultSpokenFormMapCore.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/cpp/clearSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/cpp/clearSubject2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/csharp/clearSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/csharp/clearSubject2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/java/clearSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/java/clearSubject2.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/python/clearSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/rust/changeSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scala/clearSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearSubject.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/typescript/clearSubject2.yml
packages/cursorless-vscode-e2e/src/suite/scopeProvider/runCustomSpokenFormScopeInfoTest.ts
schemas/cursorless-snippets.json

`subject, switchStatementSubject`

Switch statement subject

---

packages/cursorless-engine/src/processTargets/TargetPipelineRunner.ts
packages/cursorless-engine/src/processTargets/createContinuousRangeTarget.ts
packages/cursorless-engine/src/processTargets/modifiers/constructScopeRangeTarget.ts
packages/cursorless-engine/src/processTargets/modifiers/targetSequenceUtils.ts
packages/cursorless-engine/src/processTargets/targetUtil/createContinuousRange.ts
packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts
packages/cursorless-engine/src/processTargets/targets/InteriorTarget.ts
packages/cursorless-engine/src/processTargets/targets/LineTarget.ts
packages/cursorless-engine/src/processTargets/targets/ParagraphTarget.ts
packages/cursorless-engine/src/processTargets/targets/ScopeTypeTarget.ts
packages/cursorless-engine/src/processTargets/targets/SubTokenWordTarget.ts
packages/cursorless-engine/src/processTargets/targets/UntypedTarget.ts
packages/cursorless-engine/src/typings/target.types.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/decorations/chuckBlockAirUntilBatt.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/decorations/chuckBlockBattUntilAir.yml
packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/subtoken/chuckSecondUntilFourthWord.yml

Another attempt to remove circular dependency

---

packages/cursorless-vscode-e2e/src/suite/crossCellsSetSelection.vscode.test.ts
packages/cursorless-vscode-e2e/src/suite/editNewCell.vscode.test.ts
packages/cursorless-vscode-e2e/src/suite/intraCellSetSelection.vscode.test.ts
packages/cursorless-vscode-e2e/src/suite/skipIfWindowsCi.ts

- Fixes https://github.com/cursorless-dev/cursorless/issues/1260

Reenable notebook tests on Windows

---

packages/test-harness/package.json
pnpm-lock.yaml

This has worked in the past. Not promising that it's only a patch bump, but worth a shot

Attempt to fix Mac CI

---

package.json

Bump pnpm => 8.12.0

---

.pre-commit-config.yaml

- https://github.com/ikamensh/flynt/blob/master/CHANGELOG.md#v100
- https://github.com/astral-sh/ruff-pre-commit / https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#0111
- https://black.readthedocs.io/en/stable/integrations/source_version_control.html

pre-commit: Update Python linters

---

packages/common/src/StoredTargetKey.ts
packages/common/src/index.ts
packages/cursorless-engine/src/core/StoredTargets.ts
packages/cursorless-engine/src/processTargets/marks/StoredTargetStage.ts
packages/cursorless-vscode/src/constructTestHelpers.ts
packages/cursorless-vscode/src/extension.ts
packages/cursorless-vscode/src/storedTargetHighlighter.ts
packages/cursorless-vscode/src/usingSetting.ts

Highlight instanceReference

---

packages/common/src/StoredTargetKey.ts
packages/common/src/types/command/ActionDescriptor.ts
packages/common/src/types/command/PartialTargetDescriptor.types.ts
packages/cursorless-engine/src/CommandHistory.ts
packages/cursorless-engine/src/actions/Actions.ts
packages/cursorless-engine/src/actions/actions.types.ts
packages/cursorless-engine/src/core/commandRunner/CommandRunnerImpl.ts
packages/cursorless-engine/src/generateSpokenForm/defaultSpokenForms/actions.ts
packages/cursorless-engine/src/generateSpokenForm/defaultSpokenForms/marks.ts
packages/cursorless-engine/src/generateSpokenForm/generateSpokenForm.ts
packages/cursorless-engine/src/generateSpokenForm/primitiveTargetToSpokenForm.ts
packages/cursorless-engine/src/processTargets/MarkStageFactoryImpl.ts
packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts
packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts
packages/cursorless-vscode/src/storedTargetHighlighter.ts

- Depends on https://github.com/cursorless-dev/cursorless/pull/2170

Add keyboard special target

---

package.json
packages/cursorless-org-docs/package.json
patches/@docusaurus__theme-search-algolia@3.1.0.patch
pnpm-lock.yaml

bump docusauruas => 3.1.0

---

packages/common/src/scopeSupportFacets/scopeSupportFacetInfos.ts
packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts
packages/common/src/scopeSupportFacets/typescript.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/typescript/type.alias.scope
packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/typescript/type.alias2.scope
queries/typescript.core.scm

Fix domains for type aliases

---

.github/CODEOWNERS

Make josh codeowner of keyboard files

---

packages/cursorless-vscode/src/scripts/populateDist/populateDist.ts

Clear directories when constructing dist

---

.pre-commit-config.yaml

Fixes https://github.com/cursorless-dev/cursorless/issues/2200

Stop pre-commit from breaking our scope tests

---

.pre-commit-config.yaml
cursorless-talon/src/number_small.py
cursorless-talon/src/terms.py

Bump black to 24.1.1

---

docs/user/README.md

Clarify swap docs

---

docs/user/how-to.md
docs/user/reference/destinations.md

Add "paste" how-to guide

---

cursorless-talon/src/csv_overrides.py

- Fixes https://github.com/cursorless-dev/cursorless/issues/2165

Stop using deprecated talon setting support

---

cursorless-talon/src/cheatsheet/get_list.py
cursorless-talon/src/cheatsheet/sections/compound_targets.py
cursorless-talon/src/cheatsheet/sections/scopes.py

Fix broken cheatsheet if user has custom `"glyph"` spoken form

---

packages/cursorless-engine/src/test/fixtures/talonApi.fixture.ts

Fix unused variable warning

---

packages/cursorless-vscode-e2e/src/suite/followLink.vscode.test.ts
packages/cursorless-vscode-e2e/src/suite/scroll.vscode.test.ts

Eg https://github.com/cursorless-dev/cursorless/actions/runs/7962096184/job/21735461653

Attempt to fix CI

---

pnpm-lock.yaml

Bump `ip` => 2.0.1; `pnpm dedupe`

---

docs/user/experimental/snippets.md

Improve snippet docs

---

packages/common/src/scopeSupportFacets/typescript.ts
packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/typescript/name.field.scope
packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/typescript/type.field.scope
packages/cursorless-vscode-e2e/src/suite/fixtures/scopes/typescript/value.field.scope
queries/typescript.core.scm

Fix typescript field removal ranges

---

docs/user/how-to.md

Add VSCode task how-to doc

---

package.json

bump pnpm => 8.15.3

---

docs/contributing/adding-a-new-package.md

More adding package docs tweaks

---

pnpm-lock.yaml

bump sanitize-html => 2.12.1; pnpm dedupe

---

changelog/2024-03-addLuaSupport.md

Add changelog entry for #1962

---

packages/cursorless-engine/src/core/updateSelections/updateSelections.ts

All tests passing. ` 7211 passing (4m)`

remove unncessary function performEditsAndUpdateInternal()

---

packages/cursorless-engine/src/spokenForms/CustomSpokenForms.ts

fix uncaught exceptions from CustomSpokenForms.updateSpokenFormMaps (#2261)

---

packages/cursorless-engine/src/core/updateSelections/updateSelections.ts

minor and similar to https://github.com/cursorless-dev/cursorless/pull/2277

updateSelection minor simplification

---

.github/CODEOWNERS

Add Andreas as code owner to keyboard

---

packages/cursorless-vscode/scripts/uninstall-local.sh

Make uninstall local more robust

---

packages/cursorless-engine/src/cursorlessEngine.ts
packages/cursorless-engine/src/languages/LanguageDefinitions.ts
packages/cursorless-vscode/src/extension.ts

Was causing sidebar to not load correctly if it was open on startup. Might also address #2294 but not sure

Fix language not loaded errors

---

packages/cursorless-vscode-e2e/src/suite/scopes.vscode.test.ts

Fix assert in scope test

---

data/fixtures/scopes/csharp/ifStatement.scope
packages/common/src/scopeSupportFacets/csharp.ts
packages/common/src/scopeSupportFacets/getLanguageScopeSupport.ts
packages/cursorless-engine/src/languages/csharp.ts
queries/csharp.scm

Migrate c sharp if statement

---

packages/cursorless-engine/src/languages/LanguageDefinitions.ts

Make language loading more robust

---

data/fixtures/scopes/javascript.core/branch.switchCase.scope
queries/javascript.core.scm

typescript: Add support for default branches

---

packages/common/src/ide/normalized/NormalizedIDE.ts
packages/cursorless-engine/src/testUtil/takeSnapshot.ts
packages/cursorless-vscode-e2e/src/suite/recorded.vscode.test.ts
packages/cursorless-vscode/src/constructTestHelpers.ts
packages/vscode-common/src/TestHelpers.ts

This should also deprecate having to solve https://github.com/cursorless-dev/cursorless/issues/559

test-clipboard-cleanup

---

packages/cursorless-engine/src/languages/LegacyLanguageId.ts

remove extra legacy language ids

---

packages/cursorless-engine/src/languages/ruby.ts
queries/ruby.scm

Ruby scope migration

---

packages/common/src/cursorlessCommandIds.ts
packages/cursorless-engine/src/api/CursorlessEngineApi.ts
packages/cursorless-engine/src/cursorlessEngine.ts
packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
packages/cursorless-vscode/package.json
packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
packages/cursorless-vscode/src/registerCommands.ts

- Fixes https://github.com/cursorless-dev/cursorless/issues/2411

Add ability to repeat last cursorless command

---

packages/common/src/cursorlessCommandIds.ts
packages/cursorless-engine/src/core/StoredTargets.ts
packages/cursorless-engine/src/core/UndoStack.test.ts
packages/cursorless-engine/src/core/UndoStack.ts
packages/cursorless-engine/src/core/commandRunner/CommandRunnerImpl.ts
packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
packages/cursorless-vscode/package.json
packages/cursorless-vscode/src/extension.ts
packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
packages/cursorless-vscode/src/registerCommands.ts

- Fixes https://github.com/cursorless-dev/cursorless/issues/2413

keyboard: Undo stack for keyboard target

---

docs/contributing/test-case-recorder.md
packages/common/src/types/command/command.types.ts
packages/cursorless-engine/src/core/commandVersionUpgrades/canonicalizeAndValidateCommand.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/checkMarks.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/index.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/transformations/canonicalize.ts
packages/cursorless-engine/src/scripts/transformRecordedTests/transformations/upgrade.ts

- First step of https://github.com/cursorless-dev/cursorless/issues/2282

Add minimum version to test fixture upgrader

---

packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts
packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts
packages/cursorless-vscode/src/keyboard/TokenTypes.ts
packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts
packages/cursorless-vscode/src/keyboard/grammar/generated/grammar.ts
packages/cursorless-vscode/src/keyboard/grammar/getAcceptableTokenTypes.test.ts
packages/cursorless-vscode/src/keyboard/grammar/grammar.ne
packages/cursorless-vscode/src/keyboard/grammar/grammar.test.ts
packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json

- Fixes https://github.com/cursorless-dev/cursorless/issues/2425

keyboard: Support targeting modes for targeting selection

---

packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
packages/cursorless-vscode/src/keyboard/KeyboardCommandsTargeted.ts
packages/cursorless-vscode/src/keyboard/TokenTypes.ts
packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts
packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json

- Depends on https://github.com/cursorless-dev/cursorless/pull/2429

keyboard: Support slice ranges

---

packages/cursorless-vscode/src/keyboard/grammar/generated/grammar.ts
packages/cursorless-vscode/src/keyboard/grammar/grammar.ne

Add some types to keyboard grammar

---

data/fixtures/recorded/headTail/changeInsideTailCurly.yml
packages/cursorless-engine/src/processTargets/ModifierStageFactoryImpl.ts
packages/cursorless-engine/src/processTargets/modifiers/HeadTailStage.ts
packages/cursorless-engine/src/processTargets/targets/HeadTailTarget.ts
packages/cursorless-engine/src/processTargets/targets/index.ts
packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts

Support "inside head"

---

data/fixtures/scopes/typescript.core/value.argument.formal2.scope
queries/typescript.core.scm

Fix removal range with type

---

packages/cursorless-vscode/src/ide/vscode/VscodeFocusEditor.ts
packages/cursorless-vscode/src/ide/vscode/isDiffEditorOriginal.ts

Handle tab input being undefined

---

data/fixtures/scopes/python/collectionItem.unenclosed.iteration4.scope
data/fixtures/scopes/python/collectionItem.unenclosed7.scope
queries/python.scm

Added support for python pattern list as collection item

---

packages/cursorless-vscode/package.json
packages/file-system-common/package.json
packages/file-system-common/tsconfig.json
pnpm-lock.yaml
tsconfig.json

Added file system package

---

package.json
pnpm-lock.yaml

pnpm => 9.5.0; pnpm dedupe

---

cursorless-talon/src/get_grapheme_spoken_form_entries.py
cursorless-talon/src/spoken_forms.py
cursorless-talon/src/spoken_forms_output.py
data/fixtures/recorded/hatTokenMap/sendEmoji.yml
data/fixtures/recorded/scope/glyph/clearNextGlyphOnyx.yml
packages/cursorless-engine/src/generateSpokenForm/CustomSpokenFormGeneratorImpl.test.ts
packages/cursorless-engine/src/generateSpokenForm/primitiveTargetToSpokenForm.ts
packages/cursorless-engine/src/scopeProviders/TalonSpokenForms.ts
packages/cursorless-engine/src/spokenForms/SpokenFormType.ts
packages/cursorless-engine/src/spokenForms/defaultSpokenFormMapCore.ts
packages/cursorless-engine/src/spokenForms/graphemes.ts

Support custom spoken forms for graphemes

---

cursorless-talon/src/fallback.py

Raise exception if fallback is not found

---

packages/common/src/util/sleep.ts

Remove node from sleep util

---

docs/contributing/adding-a-new-language.md
docs/contributing/adding-a-new-scope.md

Tweak adding new language docs

---

packages/common/src/ide/normalized/NormalizedIDE.ts

Make parameter `cursorlessSnippetsDir` optional

---

packages/common/src/ide/inMemoryTextDocument/InMemoryTextDocument.ts
packages/common/src/ide/inMemoryTextDocument/InMemoryTextLine.ts
packages/common/src/ide/inMemoryTextDocument/test/InMemoryTextDocument.test.ts
packages/common/src/ide/inMemoryTextDocument/test/InMemoryTextDocumentEdit.test.ts

Added more tests. 
Fixed a bug with positionAt using crlf. 
General cleanup and simplification

In memory text editor improvements

---

.eslintrc.json
packages/common/.eslintrc.json
packages/cursorless-engine/.eslintrc.json

Lint rule to prevent node in common and engine

---

package.json
packages/cheatsheet-local/package.json
packages/cheatsheet/package.json
packages/cursorless-org-docs/package.json
packages/cursorless-org/package.json
pnpm-lock.yaml

Bumpt typescript => 5.5.3

---

packages/common/src/ide/inMemoryTextDocument/performEdits.ts
packages/common/src/ide/inMemoryTextDocument/test/InMemoryTextDocumentEdit.test.ts

Properly insert CRLF in in memory text document

---

docs/contributing/CONTRIBUTING.md
docs/contributing/test-case-recorder.md

tweak recorder docs

---

.github/CODEOWNERS

Add @phillco as codeowner

---

packages/cursorless-vscode-e2e/src/suite/tutorial/tutorial.vscode.test.ts

- Might address https://github.com/cursorless-dev/cursorless/issues/2554

tutorial: stop trying to use snapshot in tests

---

packages/cursorless-vscode-e2e/src/suite/tutorial/tutorial.vscode.test.ts

Would be nice if the test could be stricter, but don't want these were failing too much
- Fixes #2554

Improve tutorial test robustness

---

docs/contributing/tests.md

Add high-level test documentation

---

.github/workflows/deploy.yaml

Try to fix neovim deploy

---

.github/workflows/deploy.yaml
scripts/deploy-cursorless-nvim.sh

neovim: Another attempt to fix deploy

---

cursorless.nvim/LICENSE

neovim: Fix LICENSE

---

cursorless.nvim/.github/ISSUE_TEMPLATE/config.yml

neovim: Add issue templates to discourage PRs on deploy repo

---

data/fixtures/scopes/javascript.core/textFragment.comment.block.scope
data/fixtures/scopes/javascript.core/textFragment.comment.block2.scope
data/fixtures/scopes/javascript.core/textFragment.comment.line.scope
data/fixtures/scopes/javascript.core/textFragment.string.multiLine.scope
data/fixtures/scopes/javascript.core/textFragment.string.singleLine.scope
packages/common/src/scopeSupportFacets/javascript.ts
queries/javascript.core.scm

Support escape sequence in js string text fragments

---

data/fixtures/scopes/javascript.core/name.variable.pattern2.scope
data/fixtures/scopes/javascript.core/name.variable.pattern3.scope
data/fixtures/scopes/javascript.core/value.variable.pattern.scope
data/fixtures/scopes/javascript.core/value.variable.pattern2.scope
packages/common/src/scopeSupportFacets/javascript.ts
packages/common/src/scopeSupportFacets/scopeSupportFacetInfos.ts
packages/common/src/scopeSupportFacets/scopeSupportFacets.types.ts
queries/javascript.core.scm

I'm not sure if the facet names are correct for this. I picked the one I thought was closest.

Added name/value for object assignment pattern in javascript

---

packages/cursorless-vscode-e2e/src/suite/tutorial/tutorial.vscode.test.ts

Attempt to make tutorial test more robust

---

packages/cursorless-engine/src/index.ts
packages/cursorless-tutorial/src/TutorialImpl.ts
packages/cursorless-tutorial/src/TutorialStepParser.ts
packages/cursorless-tutorial/src/loadTutorial.ts
packages/cursorless-tutorial/src/stepComponentParsers/CursorlessCommandComponentParser.ts
packages/cursorless-vscode/src/createTutorial.ts
packages/cursorless-vscode/src/extension.ts

tutorial: Handle case where user has disabled a hat

---

packages/cursorless-tutorial/src/stepComponentParsers/CursorlessCommandComponentParser.ts

Clean up #2603

---

packages/test-harness/package.json
pnpm-lock.yaml

Try to fix CI by bumping `@vscode/test-electron`

---

packages/cursorless-org-docs/src/docs/user/release-notes/0.29.0.md

release notes: remove suggestions that don't work in fallback mode

---

packages/cursorless-org-docs/src/docs/user/release-notes/0.28.0.md
packages/cursorless-org-docs/src/docs/user/release-notes/0.29.0.md
packages/cursorless-org-docs/src/docs/user/release-notes/2022-year-in-review.md

Sorry couldn't help making a couple tweaks 😅. Given some of these features have been out for many months, I just wanted to make the timing clear so people didn't get thrown off

Release notes tweaks

---

packages/cursorless-org-docs/src/docs/user/release-notes/0.28.0.md
packages/cursorless-org-docs/src/docs/user/release-notes/0.29.0.md

One more minor release notes styling tweak

---

packages/cursorless-org-docs/config/algolia/README.md

Fix broken link

---

packages/cursorless-org-docs/docusaurus.config.mts

Updated docusaurus `editUrl` parameter

---

cursorless-talon/src/fallback.py

Added fallback for preferred scope

---

changelog/2024-08-joinTokens.md
data/fixtures/recorded/actions/joinBatPastEach.yml
data/fixtures/recorded/actions/joinThreeTokens.yml
data/fixtures/recorded/actions/joinTokenBattPastEach.yml
packages/cursorless-engine/src/actions/Actions.ts
packages/cursorless-engine/src/actions/JoinLines.ts
packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts
packages/cursorless-engine/src/processTargets/targets/TokenTarget.ts
packages/cursorless-engine/src/typings/target.types.ts

Added the ability to remove whitespaces with `join token`

---

.github/actions/test-neovim-lua/action.yml

Try to fix luajit ci test

---

package.json
packages/cheatsheet-local/package.json
packages/cursorless-org/package.json
pnpm-lock.yaml

- Supercedes #2662
- Supercedes #2657

bump webpack, next, pnpm

---

packages/cursorless-org/src/pages/index.tsx
packages/cursorless-vscode/package.json

Switch to cursorless-dev sponsors account

---

data/fixtures/scopes/typescript.core/namedFunction.constructor.scope
data/fixtures/scopes/typescript.core/namedFunction.method.scope
data/fixtures/scopes/typescript.core/namedFunction.scope
data/fixtures/scopes/typescript.core/statement.scope
queries/typescript.core.scm

Added support for function signatures in typescript

---

cursorless-talon/src/cheatsheet/sections/scopes.py

Added pair to the scope section of the cheatsheet

---

.github/workflows/test.yml

vscode_version was renamed to app_version, but some of the if checks were not updated

Update test workflow for app_version variable

---

.github/PULL_REQUEST_TEMPLATE.md

We'd like to experiment with putting these in the pull request because they are much easier to edit.

PULL_REQUEST_TEMPLATE.md: add release notes

---

.github/workflows/test.yml

Revert pinned version for neovim

---

packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/CollectionItemScopeHandler/CollectionItemScopeHandler.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/NotebookCellScopeHandler.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/PreferredScopeHandler.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/ScopeHandlerFactoryImpl.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SortedScopeHandler.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/SurroundingPairScopeHandler/InteriorScopeHandler.ts
packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/index.ts

Rename OneOfScopeHandler to `SortedScopeHandler`

---

packages/cursorless-vscode/src/migrateSnippets.ts

Show message about partial or skipped snippets first.

Reorder migration results

---

.github/actions/test-neovim-lua/action.yml
.github/workflows/pre-commit.yml

Fixes CI crashes.
https://github.com/cursorless-dev/cursorless/actions/runs/14496029736/job/40663909273?pr=2890

Update lua action version

---

.github/actions/lint-lua-ls/action.yml

Update install-nix-action version

---

packages/cursorless-engine/src/languages/latex.ts
packages/cursorless-engine/src/languages/scala.ts
queries/php.scm
queries/scala.scm
queries/scm.scm

Waiting for https://github.com/cursorless-dev/vscode-parse-tree/pull/103

Update queries for parse tree extension `0.35.0`

---

packages/cursorless-vscode-e2e/src/suite/scopes.vscode.test.ts

Fail scope tests with no scopes
Fixes #2844

Fail empty scope tests with empty fixtures    

---

cursorless-talon/src/fallback.py

Support scout actions in fallback

---

.github/workflows/test.yml

luarocks fails with `Error loading file: [string "/home/runner/.cache/luarocks/https___loadk.co..."]:201955: main function has more than 65536 constants`
https://github.com/cursorless-dev/cursorless/actions/runs/15364021551/job/43234618150
https://github.com/luarocks/luarocks/issues/1797

Disable neovim lua tests
